@file:JvmName("ThemeBubbleOverride")

package org.thunderdog.challegram.theme.builtin

import androidx.annotation.ColorInt
import me.vkryl.annotation.Autogenerated
import org.thunderdog.challegram.R
import org.thunderdog.challegram.theme.ThemeDelegate
import org.thunderdog.challegram.theme.ThemeId
import org.thunderdog.challegram.theme.ThemeSet

@Autogenerated open class ThemeBubbleOverride (@ThemeId id: Int, @ThemeId bubbleThemeId: Int) : ThemeDefault(id) {
  private val bubbleTheme: ThemeDelegate = ThemeSet.getBuiltinTheme(bubbleThemeId)
  
  @ColorInt override fun getColor (colorId: Int) = when (colorId) {
    R.id.theme_color_bubbleOut_background,
    R.id.theme_color_bubbleOut_time,
    R.id.theme_color_bubbleOut_progress,
    R.id.theme_color_bubbleOut_text,
    R.id.theme_color_bubbleOut_textLink,
    R.id.theme_color_bubbleOut_textLinkPressHighlight,
    R.id.theme_color_bubbleOut_outline,
    R.id.theme_color_bubbleOut_separator,
    R.id.theme_color_bubbleOut_pressed,
    R.id.theme_color_bubbleOut_chatVerticalLine,
    R.id.theme_color_bubbleOut_chatNeutralFillingContent,
    R.id.theme_color_bubbleOut_chatCorrectFilling,
    R.id.theme_color_bubbleOut_chatCorrectFillingContent,
    R.id.theme_color_bubbleOut_chatCorrectChosenFilling,
    R.id.theme_color_bubbleOut_chatCorrectChosenFillingContent,
    R.id.theme_color_bubbleOut_chatNegativeFilling,
    R.id.theme_color_bubbleOut_chatNegativeFillingContent,
    R.id.theme_color_bubbleOut_inlineText,
    R.id.theme_color_bubbleOut_inlineOutline,
    R.id.theme_color_bubbleOut_inlineIcon,
    R.id.theme_color_bubbleOut_waveformActive,
    R.id.theme_color_bubbleOut_waveformInactive,
    R.id.theme_color_bubbleOut_file,
    R.id.theme_color_bubbleOut_ticks,
    R.id.theme_color_bubbleOut_ticksRead,
    R.id.theme_color_bubbleOut_messageAuthor,
    R.id.theme_color_bubbleOut_messageAuthorPsa -> bubbleTheme.getColor(colorId)
    else -> super.getColor(colorId)
  }
}