@file:JvmName("ThemeBlackWhite")

package org.thunderdog.challegram.theme.builtin

import androidx.annotation.ColorInt
import me.vkryl.annotation.Autogenerated
import org.thunderdog.challegram.R
import org.thunderdog.challegram.theme.ThemeId
import org.thunderdog.challegram.theme.ThemeColorId
import org.thunderdog.challegram.theme.ThemeProperty
import org.thunderdog.challegram.theme.ThemeInherited

@Autogenerated class ThemeBlackWhite : ThemeInherited(ThemeId.BLACK_WHITE, ThemeId.NIGHT_BLACK) {
  override fun getProperty (@ThemeProperty propertyId: Int): Float = when (propertyId) {
    ThemeProperty.BUBBLE_OUTLINE, ThemeProperty.REPLACE_SHADOWS_WITH_SEPARATORS ->
      1.0f
    ThemeProperty.PARENT_THEME ->
      2.0f
    else -> super.getProperty(propertyId)
  }

  @ColorInt override fun getColor (@ThemeColorId colorId: Int): Int = when (colorId) {
    R.id.theme_color_badgeFailed ->
      -9408352 // 0xff7070a0
    R.id.theme_color_badgeMuted, R.id.theme_color_togglerInactiveBackground ->
      -9408400 // 0xff707070
    R.id.theme_color_bubble_chatSeparator, R.id.theme_color_bubbleIn_outline, R.id.theme_color_bubbleIn_separator, R.id.theme_color_bubbleOut_outline, R.id.theme_color_chatSeparator, R.id.theme_color_inputInactive, R.id.theme_color_separator, R.id.theme_color_shareSeparator ->
      -14211289 // 0xff272727
    R.id.theme_color_bubbleIn_textLink, R.id.theme_color_bubbleOut_textLink, R.id.theme_color_iv_textLink, R.id.theme_color_iv_textMarkedLink, R.id.theme_color_textLink ->
      -6250336 // 0xffa0a0a0
    R.id.theme_color_bubbleIn_textLinkPressHighlight, R.id.theme_color_iv_textLinkPressHighlight, R.id.theme_color_textLinkPressHighlight ->
      2007015584 // 0x77a0a0a0
    R.id.theme_color_bubbleOut_waveformActive, R.id.theme_color_messageAuthor, R.id.theme_color_notification, R.id.theme_color_notificationPlayer, R.id.theme_color_waveformActive ->
      -1 // 0xffffffff
    R.id.theme_color_chatListIcon, R.id.theme_color_chatListMute ->
      -8947849 // 0xff777777
    R.id.theme_color_circleButtonNewChannel, R.id.theme_color_circleButtonNewChat, R.id.theme_color_circleButtonNewGroup, R.id.theme_color_circleButtonNewSecret ->
      -14803426 // 0xff1e1e1e
    R.id.theme_color_file, R.id.theme_color_fileGreen, R.id.theme_color_fileRed, R.id.theme_color_fileYellow ->
      -14013910 // 0xff2a2a2a
    R.id.theme_color_filling, R.id.theme_color_headerLightBackground ->
      -16777216 // 0xff000000
    R.id.theme_color_headerBackground, R.id.theme_color_passcode ->
      -15724528 // 0xff101010
    R.id.theme_color_iconLight ->
      -10790053 // 0xff5b5b5b
    R.id.theme_color_messageSelection ->
      452984831 // 0x1affffff
    R.id.theme_color_togglerActiveBackground ->
      -4539718 // 0xffbababa
    R.id.theme_color_togglerInactive ->
      -7303024 // 0xff909090
    else -> super.getColor(colorId)
  }
}