@file:JvmName("ThemeRed")

package org.thunderdog.challegram.theme.builtin

import androidx.annotation.ColorInt
import me.vkryl.annotation.Autogenerated
import org.thunderdog.challegram.R
import org.thunderdog.challegram.theme.ThemeId
import org.thunderdog.challegram.theme.ThemeColorIdTinted
import org.thunderdog.challegram.theme.ThemeProperty

@Autogenerated class ThemeRed : ThemeDefault(ThemeId.RED) {
  override fun getProperty (@ThemeProperty propertyId: Int): Float = when (propertyId) {
    ThemeProperty.PARENT_THEME ->
      1.0f
    else -> super.getProperty(propertyId)
  }

  @ColorInt override fun getColor (@ThemeColorIdTinted colorId: Int): Int = when (colorId) {
    R.id.theme_color_badge, R.id.theme_color_bubbleIn_progress, R.id.theme_color_bubbleOut_file, R.id.theme_color_bubbleOut_waveformActive, R.id.theme_color_chatListAction, R.id.theme_color_chatSendButton, R.id.theme_color_circleButtonActive, R.id.theme_color_circleButtonRegular, R.id.theme_color_circleButtonTheme, R.id.theme_color_controlActive, R.id.theme_color_file, R.id.theme_color_fileRed, R.id.theme_color_headerBarCallActive, R.id.theme_color_playerButtonActive, R.id.theme_color_profileSectionActive, R.id.theme_color_progress, R.id.theme_color_promo, R.id.theme_color_snackbarUpdate, R.id.theme_color_textSearchQueryHighlight, R.id.theme_color_waveformActive ->
      -769226 // 0xfff44336
    R.id.theme_color_bubbleIn_textLink, R.id.theme_color_bubbleOut_chatCorrectChosenFilling, R.id.theme_color_bubbleOut_chatCorrectFilling, R.id.theme_color_bubbleOut_chatVerticalLine, R.id.theme_color_bubbleOut_textLink, R.id.theme_color_chatListVerify, R.id.theme_color_inputActive, R.id.theme_color_iv_textLink, R.id.theme_color_iv_textMarkedLink, R.id.theme_color_messageCorrectChosenFilling, R.id.theme_color_messageCorrectFilling, R.id.theme_color_messageVerticalLine, R.id.theme_color_seekDone, R.id.theme_color_sliderActive, R.id.theme_color_textLink, R.id.theme_color_textNeutral ->
      -1092784 // 0xffef5350
    R.id.theme_color_bubbleIn_textLinkPressHighlight, R.id.theme_color_bubbleOut_textLinkPressHighlight, R.id.theme_color_iv_textLinkPressHighlight, R.id.theme_color_iv_textMarkedLinkPressHighlight, R.id.theme_color_textLinkPressHighlight ->
      1089426256 // 0x40ef5350
    R.id.theme_color_bubbleOut_background ->
      -72733 // 0xfffee3e3
    R.id.theme_color_bubbleOut_inlineIcon, R.id.theme_color_inlineIcon, R.id.theme_color_messageSwipeBackground ->
      -2937041 // 0xffd32f2f
    R.id.theme_color_bubbleOut_inlineOutline, R.id.theme_color_bubbleOut_inlineText, R.id.theme_color_bubbleOut_messageAuthor, R.id.theme_color_checkActive, R.id.theme_color_inlineOutline, R.id.theme_color_inlineText, R.id.theme_color_messageAuthor, R.id.theme_color_online, R.id.theme_color_profileSectionActiveContent, R.id.theme_color_togglerActive, R.id.theme_color_unreadText ->
      -1754827 // 0xffe53935
    R.id.theme_color_bubbleOut_progress, R.id.theme_color_bubbleOut_separator, R.id.theme_color_bubbleOut_time ->
      -4292479 // 0xffbe8081
    R.id.theme_color_bubbleOut_ticks, R.id.theme_color_bubbleOut_ticksRead, R.id.theme_color_iconActive, R.id.theme_color_ticks, R.id.theme_color_ticksRead ->
      -1427147 // 0xffea3935
    R.id.theme_color_bubbleOut_waveformInactive ->
      -344638 // 0xfffabdc2
    R.id.theme_color_headerBackground, R.id.theme_color_notification, R.id.theme_color_notificationLink, R.id.theme_color_notificationPlayer, R.id.theme_color_passcode ->
      -3790808 // 0xffc62828
    R.id.theme_color_messageSelection ->
      280435740 // 0x10b71c1c
    R.id.theme_color_seekReady ->
      -273197 // 0xfffbd4d3
    R.id.theme_color_textNegative ->
      -4776932 // 0xffb71c1c
    R.id.theme_color_textSelectionHighlight ->
      -742228 // 0xfff4acac
    R.id.theme_color_togglerActiveBackground ->
      -1074534 // 0xffef9a9a
    R.id.theme_color_unread ->
      -5138 // 0xffffebee
    R.id.theme_color_waveformInactive ->
      -12846 // 0xffffcdd2
    else -> super.getColor(colorId)
  }
}