@file:JvmName("ThemeWhiteBlack")

package org.thunderdog.challegram.theme.builtin

import me.vkryl.annotation.Autogenerated
import org.thunderdog.challegram.theme.ThemeId
import org.thunderdog.challegram.theme.ThemeProperty

@Autogenerated class ThemeWhiteBlack : ThemeDefault(ThemeId.WHITE_BLACK) {
  override fun getProperty (@ThemeProperty propertyId: Int): Float = when (propertyId) {
    ThemeProperty.PARENT_THEME ->
      1.0f
    else -> super.getProperty(propertyId)
  }
}