@file:JvmName("ThemeGreen")

package org.thunderdog.challegram.theme.builtin

import androidx.annotation.ColorInt
import me.vkryl.annotation.Autogenerated
import org.thunderdog.challegram.R
import org.thunderdog.challegram.theme.ThemeId
import org.thunderdog.challegram.theme.ThemeColorIdTinted
import org.thunderdog.challegram.theme.ThemeProperty

@Autogenerated class ThemeGreen : ThemeDefault(ThemeId.GREEN) {
  override fun getProperty (@ThemeProperty propertyId: Int): Float = when (propertyId) {
    ThemeProperty.PARENT_THEME ->
      1.0f
    else -> super.getProperty(propertyId)
  }

  @ColorInt override fun getColor (@ThemeColorIdTinted colorId: Int): Int = when (colorId) {
    R.id.theme_color_badge, R.id.theme_color_bubbleIn_textLink, R.id.theme_color_bubbleOut_inlineOutline, R.id.theme_color_bubbleOut_textLink, R.id.theme_color_bubbleOut_ticks, R.id.theme_color_bubbleOut_ticksRead, R.id.theme_color_bubbleOut_waveformActive, R.id.theme_color_chatListAction, R.id.theme_color_checkActive, R.id.theme_color_iconActive, R.id.theme_color_inlineOutline, R.id.theme_color_iv_textLink, R.id.theme_color_iv_textMarkedLink, R.id.theme_color_messageSwipeBackground, R.id.theme_color_online, R.id.theme_color_profileSectionActiveContent, R.id.theme_color_textLink, R.id.theme_color_ticks, R.id.theme_color_ticksRead, R.id.theme_color_togglerActive, R.id.theme_color_unreadText, R.id.theme_color_waveformActive ->
      -11751600 // 0xff4caf50
    R.id.theme_color_bubbleIn_progress, R.id.theme_color_bubbleOut_chatCorrectChosenFilling, R.id.theme_color_bubbleOut_chatCorrectFilling, R.id.theme_color_bubbleOut_chatVerticalLine, R.id.theme_color_chatListVerify, R.id.theme_color_circleButtonActive, R.id.theme_color_circleButtonRegular, R.id.theme_color_circleButtonTheme, R.id.theme_color_controlActive, R.id.theme_color_headerBarCallActive, R.id.theme_color_inputActive, R.id.theme_color_messageCorrectChosenFilling, R.id.theme_color_messageCorrectFilling, R.id.theme_color_messageVerticalLine, R.id.theme_color_progress, R.id.theme_color_seekDone, R.id.theme_color_sliderActive, R.id.theme_color_snackbarUpdate, R.id.theme_color_textNeutral ->
      -10044566 // 0xff66bb6a
    R.id.theme_color_bubbleIn_textLinkPressHighlight, R.id.theme_color_bubbleOut_textLinkPressHighlight, R.id.theme_color_iv_textLinkPressHighlight, R.id.theme_color_iv_textMarkedLinkPressHighlight, R.id.theme_color_textLinkPressHighlight, R.id.theme_color_tooltip_textLinkPressHighlight ->
      1078767440 // 0x404caf50
    R.id.theme_color_bubbleOut_background ->
      -1049122 // 0xffeffdde
    R.id.theme_color_bubbleOut_file, R.id.theme_color_file, R.id.theme_color_playerButtonActive ->
      -8862081 // 0xff78c67f
    R.id.theme_color_bubbleOut_inlineIcon, R.id.theme_color_bubbleOut_inlineText, R.id.theme_color_bubbleOut_messageAuthor, R.id.theme_color_chatSendButton, R.id.theme_color_headerBackground, R.id.theme_color_inlineIcon, R.id.theme_color_inlineText, R.id.theme_color_messageAuthor, R.id.theme_color_notification, R.id.theme_color_notificationLink, R.id.theme_color_notificationPlayer, R.id.theme_color_passcode, R.id.theme_color_profileSectionActive ->
      -12345273 // 0xff43a047
    R.id.theme_color_bubbleOut_outline ->
      -4797475 // 0xffb6cbdd
    R.id.theme_color_bubbleOut_progress, R.id.theme_color_bubbleOut_separator, R.id.theme_color_bubbleOut_time ->
      -9649564 // 0xff6cc264
    R.id.theme_color_bubbleOut_waveformInactive, R.id.theme_color_textSelectionHighlight, R.id.theme_color_waveformInactive ->
      -3610935 // 0xffc8e6c9
    R.id.theme_color_messageSelection ->
      275168106 // 0x1066bb6a
    R.id.theme_color_promo, R.id.theme_color_textSearchQueryHighlight, R.id.theme_color_tooltip_textLink ->
      -8271996 // 0xff81c784
    R.id.theme_color_seekReady ->
      -2494758 // 0xffd9eeda
    R.id.theme_color_togglerActiveBackground ->
      -5908825 // 0xffa5d6a7
    R.id.theme_color_unread ->
      -1509911 // 0xffe8f5e9
    else -> super.getColor(colorId)
  }
}