@file:JvmName("ThemeNightBlue")

package org.thunderdog.challegram.theme.builtin

import androidx.annotation.ColorInt
import me.vkryl.annotation.Autogenerated
import org.thunderdog.challegram.R
import org.thunderdog.challegram.theme.ThemeId
import org.thunderdog.challegram.theme.ThemeColorId
import org.thunderdog.challegram.theme.ThemeProperty

@Autogenerated class ThemeNightBlue : ThemeDefault(ThemeId.NIGHT_BLUE) {
  override fun getProperty (@ThemeProperty propertyId: Int): Float = when (propertyId) {
    ThemeProperty.DARK, ThemeProperty.PARENT_THEME, ThemeProperty.SHADOW_DEPTH, ThemeProperty.WALLPAPER_USAGE_ID ->
      1.0f
    else -> super.getProperty(propertyId)
  }

  @ColorInt override fun getColor (@ThemeColorId colorId: Int): Int = when (colorId) {
    R.id.theme_color_attachContact, R.id.theme_color_attachFile, R.id.theme_color_attachInlineBot, R.id.theme_color_attachLocation, R.id.theme_color_attachPhoto, R.id.theme_color_bubble_mediaReply_noWallpaper, R.id.theme_color_bubble_unread_noWallpaper, R.id.theme_color_bubbleIn_background, R.id.theme_color_circleButtonChat, R.id.theme_color_circleButtonOverlay, R.id.theme_color_filling, R.id.theme_color_overlayFilling, R.id.theme_color_unread ->
      -14932173 // 0xff1c2733
    R.id.theme_color_background, R.id.theme_color_chatBackground, R.id.theme_color_chatKeyboard, R.id.theme_color_iv_chatLinkBackground, R.id.theme_color_iv_preBlockBackground, R.id.theme_color_iv_textCodeBackground, R.id.theme_color_iv_textCodeBackgroundPressed ->
      -15393498 // 0xff151d26
    R.id.theme_color_background_icon, R.id.theme_color_badgeMuted, R.id.theme_color_bubbleIn_time, R.id.theme_color_circleButtonChatIcon, R.id.theme_color_circleButtonOverlayIcon, R.id.theme_color_icon, R.id.theme_color_iv_caption, R.id.theme_color_iv_icon, R.id.theme_color_iv_pageAuthor, R.id.theme_color_iv_pageFooter, R.id.theme_color_textLight, R.id.theme_color_textPlaceholder ->
      -8548712 // 0xff7d8e98
    R.id.theme_color_background_text, R.id.theme_color_background_textLight ->
      -8746606 // 0xff7a8992
    R.id.theme_color_badge, R.id.theme_color_bubbleOut_ticksRead, R.id.theme_color_chatListAction, R.id.theme_color_chatListVerify, R.id.theme_color_checkActive, R.id.theme_color_iconActive, R.id.theme_color_seekDone, R.id.theme_color_sliderActive, R.id.theme_color_ticks, R.id.theme_color_ticksRead ->
      -10901278 // 0xff59a8e2
    R.id.theme_color_badgeMutedText ->
      -16777216 // 0xff000000
    R.id.theme_color_bubble_button_noWallpaper, R.id.theme_color_bubble_buttonRipple_noWallpaper ->
      805306368 // 0x30000000
    R.id.theme_color_bubble_chatSeparator, R.id.theme_color_bubbleIn_outline, R.id.theme_color_bubbleIn_separator, R.id.theme_color_bubbleOut_outline, R.id.theme_color_chatSeparator, R.id.theme_color_inputInactive, R.id.theme_color_iv_separator, R.id.theme_color_separator, R.id.theme_color_shareSeparator ->
      -15722722 // 0xff10171e
    R.id.theme_color_bubble_date, R.id.theme_color_bubble_date_noWallpaper, R.id.theme_color_bubble_overlay ->
      1712659750 // 0x66151d26
    R.id.theme_color_bubble_messageSelection, R.id.theme_color_bubbleIn_pressed ->
      536870912 // 0x20000000
    R.id.theme_color_bubble_messageSelectionNoWallpaper ->
      704643072 // 0x2a000000
    R.id.theme_color_bubbleIn_progress, R.id.theme_color_chatSendButton, R.id.theme_color_controlActive, R.id.theme_color_inputActive, R.id.theme_color_profileSectionActive, R.id.theme_color_profileSectionActiveContent, R.id.theme_color_progress, R.id.theme_color_promo, R.id.theme_color_textNeutral, R.id.theme_color_textSearchQueryHighlight, R.id.theme_color_togglerActive, R.id.theme_color_togglerPositive ->
      -10170627 // 0xff64cefd
    R.id.theme_color_bubbleIn_text, R.id.theme_color_bubbleOut_text, R.id.theme_color_drawerText, R.id.theme_color_headerButtonIcon, R.id.theme_color_headerLightIcon, R.id.theme_color_headerLightText, R.id.theme_color_introSectionActive, R.id.theme_color_iv_blockQuoteLine, R.id.theme_color_iv_header, R.id.theme_color_iv_pageTitle, R.id.theme_color_iv_text, R.id.theme_color_iv_textCode, R.id.theme_color_iv_textMarked, R.id.theme_color_iv_textReference, R.id.theme_color_playerButton, R.id.theme_color_text, R.id.theme_color_themeBlackWhite, R.id.theme_color_unreadText ->
      -1 // 0xffffffff
    R.id.theme_color_bubbleIn_textLink, R.id.theme_color_circleButtonActive, R.id.theme_color_circleButtonRegular, R.id.theme_color_circleButtonTheme, R.id.theme_color_headerButton, R.id.theme_color_iv_textLink, R.id.theme_color_iv_textMarkedLink, R.id.theme_color_messageAuthor, R.id.theme_color_notificationLink, R.id.theme_color_snackbarUpdate, R.id.theme_color_textLink ->
      -10376735 // 0xff61a9e1
    R.id.theme_color_bubbleIn_textLinkPressHighlight, R.id.theme_color_iv_textLinkPressHighlight, R.id.theme_color_textLinkPressHighlight ->
      1147251169 // 0x4461a9e1
    R.id.theme_color_bubbleOut_background, R.id.theme_color_messageSwipeBackground ->
      -12227949 // 0xff456a93
    R.id.theme_color_bubbleOut_chatCorrectChosenFilling, R.id.theme_color_bubbleOut_chatCorrectFilling, R.id.theme_color_bubbleOut_chatVerticalLine, R.id.theme_color_bubbleOut_inlineIcon, R.id.theme_color_bubbleOut_inlineOutline, R.id.theme_color_bubbleOut_inlineText, R.id.theme_color_bubbleOut_messageAuthor, R.id.theme_color_bubbleOut_textLink, R.id.theme_color_bubbleOut_ticks, R.id.theme_color_messageCorrectChosenFilling, R.id.theme_color_messageCorrectFilling ->
      -7943425 // 0xff86caff
    R.id.theme_color_bubbleOut_file, R.id.theme_color_bubbleOut_waveformActive, R.id.theme_color_file ->
      -10376991 // 0xff61a8e1
    R.id.theme_color_bubbleOut_progress, R.id.theme_color_bubbleOut_separator, R.id.theme_color_bubbleOut_time ->
      -7229496 // 0xff91afc8
    R.id.theme_color_bubbleOut_textLinkPressHighlight ->
      1082575615 // 0x4086caff
    R.id.theme_color_bubbleOut_waveformInactive, R.id.theme_color_waveformInactive ->
      -9727571 // 0xff6b91ad
    R.id.theme_color_chatKeyboardButton ->
      -14606047 // 0xff212121
    R.id.theme_color_chatListIcon, R.id.theme_color_chatListMute, R.id.theme_color_togglerInactive ->
      -8745319 // 0xff7a8e99
    R.id.theme_color_controlInactive, R.id.theme_color_sliderInactive, R.id.theme_color_togglerInactiveBackground ->
      -11970202 // 0xff495966
    R.id.theme_color_drawer, R.id.theme_color_statusBar ->
      1073741824 // 0x40000000
    R.id.theme_color_fileAttach, R.id.theme_color_playerCoverPlaceholder ->
      -15327448 // 0xff161f28
    R.id.theme_color_fillingPressed ->
      -14671840 // 0xff202020
    R.id.theme_color_headerBackground, R.id.theme_color_headerLightBackground, R.id.theme_color_notification, R.id.theme_color_notificationPlayer, R.id.theme_color_passcode ->
      -14537156 // 0xff222e3c
    R.id.theme_color_headerPlaceholder ->
      285212671 // 0x10ffffff
    R.id.theme_color_iconLight ->
      -11248797 // 0xff545b63
    R.id.theme_color_inlineIcon, R.id.theme_color_inlineOutline, R.id.theme_color_inlineText ->
      -10508068 // 0xff5fa8dc
    R.id.theme_color_introSection ->
      -8289919 // 0xff818181
    R.id.theme_color_iv_blockQuote ->
      -197380 // 0xfffcfcfc
    R.id.theme_color_iv_pageSubtitle ->
      -8285540 // 0xff81929c
    R.id.theme_color_iv_pullQuote ->
      -394759 // 0xfff9f9f9
    R.id.theme_color_iv_textReferenceBackground ->
      720564978 // 0x2af2f2f2
    R.id.theme_color_iv_textReferenceBackgroundPressed ->
      820044000 // 0x30e0e0e0
    R.id.theme_color_iv_textReferenceOutline ->
      1157627903 // 0x44ffffff
    R.id.theme_color_iv_textReferenceOutlinePressed ->
      553648127 // 0x20ffffff
    R.id.theme_color_messageSelection ->
      274835937 // 0x1061a9e1
    R.id.theme_color_messageVerticalLine ->
      -11301187 // 0xff538ebd
    R.id.theme_color_nameInactive, R.id.theme_color_themeNightBlack ->
      -9803158 // 0xff6a6a6a
    R.id.theme_color_notificationSecure, R.id.theme_color_textSecure ->
      -8854914 // 0xff78e27e
    R.id.theme_color_placeholder ->
      218103807 // 0x0cffffff
    R.id.theme_color_playerButtonActive ->
      -10967328 // 0xff58a6e0
    R.id.theme_color_playerCoverIcon ->
      -9865086 // 0xff697882
    R.id.theme_color_previewBackground ->
      1879048192 // 0x70000000
    R.id.theme_color_seekEmpty ->
      -15525084 // 0xff131b24
    R.id.theme_color_seekReady ->
      -14008754 // 0xff2a3e4e
    R.id.theme_color_textSelectionHighlight ->
      -13285539 // 0xff35475d
    R.id.theme_color_togglerActiveBackground, R.id.theme_color_togglerPositiveBackground ->
      -12487273 // 0xff417597
    R.id.theme_color_tooltip ->
      -301989888 // 0xee000000
    R.id.theme_color_tooltip_outline ->
      541420179 // 0x20456a93
    R.id.theme_color_waveformActive ->
      -14332834 // 0xff254c5e
    else -> super.getColor(colorId)
  }
}