@file:JvmName("ThemeNightBlack")

package org.thunderdog.challegram.theme.builtin

import androidx.annotation.ColorInt
import me.vkryl.annotation.Autogenerated
import org.thunderdog.challegram.R
import org.thunderdog.challegram.theme.ThemeId
import org.thunderdog.challegram.theme.ThemeColorId
import org.thunderdog.challegram.theme.ThemeProperty

@Autogenerated class ThemeNightBlack : ThemeDefault(ThemeId.NIGHT_BLACK) {
  override fun getProperty (@ThemeProperty propertyId: Int): Float = when (propertyId) {
    ThemeProperty.DARK, ThemeProperty.PARENT_THEME, ThemeProperty.SHADOW_DEPTH, ThemeProperty.WALLPAPER_USAGE_ID ->
      1.0f
    else -> super.getProperty(propertyId)
  }

  @ColorInt override fun getColor (@ThemeColorId colorId: Int): Int = when (colorId) {
    R.id.theme_color_attachContact, R.id.theme_color_attachFile, R.id.theme_color_attachInlineBot, R.id.theme_color_attachLocation, R.id.theme_color_attachPhoto, R.id.theme_color_badgeMutedText, R.id.theme_color_badgeText, R.id.theme_color_bubbleIn_background, R.id.theme_color_bubbleOut_background, R.id.theme_color_chatKeyboardButton, R.id.theme_color_headerBackground, R.id.theme_color_headerBarCallMuted, R.id.theme_color_headerLightBackground, R.id.theme_color_inlineContentActive, R.id.theme_color_iv_preBlockBackground, R.id.theme_color_iv_textCodeBackground, R.id.theme_color_iv_textCodeBackgroundPressed, R.id.theme_color_messageSwipeBackground, R.id.theme_color_notification, R.id.theme_color_notificationPlayer, R.id.theme_color_passcode, R.id.theme_color_unread ->
      -14606047 // 0xff212121
    R.id.theme_color_avatarBlue, R.id.theme_color_avatarBlue_big, R.id.theme_color_nameBlue ->
      -8338950 // 0xff80c1fa
    R.id.theme_color_avatarCyan, R.id.theme_color_avatarCyan_big, R.id.theme_color_nameCyan ->
      -9648164 // 0xff6cc7dc
    R.id.theme_color_avatarGreen, R.id.theme_color_avatarGreen_big, R.id.theme_color_bubbleOut_messageAuthorPsa, R.id.theme_color_messageAuthorPsa, R.id.theme_color_nameGreen ->
      -7551634 // 0xff8cc56e
    R.id.theme_color_avatarOrange, R.id.theme_color_avatarOrange_big, R.id.theme_color_nameOrange ->
      -745623 // 0xfff49f69
    R.id.theme_color_avatarPink, R.id.theme_color_avatarPink_big, R.id.theme_color_namePink ->
      -1998420 // 0xffe181ac
    R.id.theme_color_avatarRed, R.id.theme_color_avatarRed_big, R.id.theme_color_nameRed ->
      -1017483 // 0xfff07975
    R.id.theme_color_avatarViolet, R.id.theme_color_avatarViolet_big, R.id.theme_color_nameViolet ->
      -4410375 // 0xffbcb3f9
    R.id.theme_color_avatarYellow, R.id.theme_color_avatarYellow_big, R.id.theme_color_nameYellow ->
      -407478 // 0xfff9c84a
    R.id.theme_color_background, R.id.theme_color_bubble_chatSeparator, R.id.theme_color_bubbleIn_outline, R.id.theme_color_bubbleIn_separator, R.id.theme_color_bubbleOut_chatCorrectChosenFillingContent, R.id.theme_color_bubbleOut_chatCorrectFillingContent, R.id.theme_color_bubbleOut_chatNeutralFillingContent, R.id.theme_color_bubbleOut_outline, R.id.theme_color_chatKeyboard, R.id.theme_color_chatSeparator, R.id.theme_color_checkContent, R.id.theme_color_controlContent, R.id.theme_color_iv_chatLinkBackground, R.id.theme_color_messageCorrectChosenFillingContent, R.id.theme_color_messageCorrectFillingContent, R.id.theme_color_messageNegativeLineContent, R.id.theme_color_messageNeutralFillingContent, R.id.theme_color_promoContent, R.id.theme_color_separator, R.id.theme_color_shareSeparator, R.id.theme_color_togglerPositiveContent, R.id.theme_color_circleButtonActiveIcon ->
      -16777216 // 0xff000000
    R.id.theme_color_background_icon, R.id.theme_color_background_text, R.id.theme_color_background_textLight, R.id.theme_color_bubbleIn_time, R.id.theme_color_bubbleOut_progress, R.id.theme_color_bubbleOut_separator, R.id.theme_color_bubbleOut_time, R.id.theme_color_circleButtonChatIcon, R.id.theme_color_circleButtonOverlayIcon, R.id.theme_color_icon, R.id.theme_color_iv_caption, R.id.theme_color_iv_icon, R.id.theme_color_iv_pageAuthor, R.id.theme_color_iv_pageFooter, R.id.theme_color_textLight, R.id.theme_color_textPlaceholder ->
      -6250336 // 0xffa0a0a0
    R.id.theme_color_badge, R.id.theme_color_bubbleIn_progress, R.id.theme_color_bubbleIn_text, R.id.theme_color_bubbleOut_chatCorrectChosenFilling, R.id.theme_color_bubbleOut_chatCorrectFilling, R.id.theme_color_bubbleOut_chatVerticalLine, R.id.theme_color_bubbleOut_inlineIcon, R.id.theme_color_bubbleOut_inlineOutline, R.id.theme_color_bubbleOut_inlineText, R.id.theme_color_bubbleOut_text, R.id.theme_color_bubbleOut_ticks, R.id.theme_color_bubbleOut_ticksRead, R.id.theme_color_chatListAction, R.id.theme_color_chatListVerify, R.id.theme_color_chatSendButton, R.id.theme_color_checkActive, R.id.theme_color_controlActive, R.id.theme_color_headerButtonIcon, R.id.theme_color_headerLightIcon, R.id.theme_color_headerLightText, R.id.theme_color_iconActive, R.id.theme_color_inlineIcon, R.id.theme_color_inlineOutline, R.id.theme_color_inlineText, R.id.theme_color_inputActive, R.id.theme_color_introSectionActive, R.id.theme_color_iv_blockQuoteLine, R.id.theme_color_iv_header, R.id.theme_color_iv_pageTitle, R.id.theme_color_iv_text, R.id.theme_color_iv_textCode, R.id.theme_color_iv_textMarked, R.id.theme_color_iv_textReference, R.id.theme_color_messageCorrectChosenFilling, R.id.theme_color_messageCorrectFilling, R.id.theme_color_messageVerticalLine, R.id.theme_color_notificationLink, R.id.theme_color_online, R.id.theme_color_playerButton, R.id.theme_color_profileSectionActive, R.id.theme_color_profileSectionActiveContent, R.id.theme_color_progress, R.id.theme_color_promo, R.id.theme_color_sliderActive, R.id.theme_color_text, R.id.theme_color_textNeutral, R.id.theme_color_themeBlackWhite, R.id.theme_color_ticks, R.id.theme_color_ticksRead, R.id.theme_color_togglerActive, R.id.theme_color_togglerPositive, R.id.theme_color_unreadText, R.id.theme_color_circleButtonActive ->
      -1 // 0xffffffff
    R.id.theme_color_badgeMuted, R.id.theme_color_controlInactive, R.id.theme_color_nameInactive, R.id.theme_color_themeNightBlack, R.id.theme_color_togglerInactiveBackground ->
      -9803158 // 0xff6a6a6a
    R.id.theme_color_bubble_button_noWallpaper, R.id.theme_color_bubble_buttonRipple_noWallpaper ->
      547397792 // 0x20a0a0a0
    R.id.theme_color_bubble_date_noWallpaper, R.id.theme_color_bubble_mediaReply_noWallpaper, R.id.theme_color_bubble_overlay, R.id.theme_color_bubble_unread_noWallpaper ->
      1084268704 // 0x40a0a0a0
    R.id.theme_color_bubble_messageCheckOutline ->
      -1381654 // 0xffeaeaea
    R.id.theme_color_bubble_messageCheckOutlineNoWallpaper ->
      -9671572 // 0xff6c6c6c
    R.id.theme_color_bubble_messageSelection, R.id.theme_color_iv_textReferenceOutlinePressed ->
      553648127 // 0x20ffffff
    R.id.theme_color_bubble_messageSelectionNoWallpaper ->
      452984831 // 0x1affffff
    R.id.theme_color_bubbleIn_pressed, R.id.theme_color_bubbleOut_pressed ->
      536870912 // 0x20000000
    R.id.theme_color_bubbleIn_textLink, R.id.theme_color_bubbleOut_messageAuthor, R.id.theme_color_bubbleOut_textLink, R.id.theme_color_iv_textLink, R.id.theme_color_iv_textMarkedLink, R.id.theme_color_messageAuthor, R.id.theme_color_textLink, R.id.theme_color_textSearchQueryHighlight, R.id.theme_color_tooltip_textLink ->
      -8750470 // 0xff7a7a7a
    R.id.theme_color_bubbleIn_textLinkPressHighlight, R.id.theme_color_bubbleOut_textLinkPressHighlight, R.id.theme_color_iv_textLinkPressHighlight, R.id.theme_color_iv_textMarkedLinkPressHighlight, R.id.theme_color_seekReady, R.id.theme_color_textLinkPressHighlight, R.id.theme_color_tooltip_textLinkPressHighlight ->
      1081768570 // 0x407a7a7a
    R.id.theme_color_bubbleOut_file, R.id.theme_color_file, R.id.theme_color_fileAttach, R.id.theme_color_inputInactive ->
      -12961222 // 0xff3a3a3a
    R.id.theme_color_bubbleOut_waveformActive, R.id.theme_color_waveformActive ->
      -3487030 // 0xffcacaca
    R.id.theme_color_bubbleOut_waveformInactive, R.id.theme_color_fillingPositive, R.id.theme_color_waveformInactive ->
      -13619152 // 0xff303030
    R.id.theme_color_chatBackground, R.id.theme_color_filling ->
      -15461356 // 0xff141414
    R.id.theme_color_chatListIcon, R.id.theme_color_chatListMute ->
      -9341316 // 0xff71767c
    R.id.theme_color_circleButtonChat, R.id.theme_color_circleButtonOverlay, R.id.theme_color_circleButtonRegular, R.id.theme_color_circleButtonTheme, R.id.theme_color_headerButton, R.id.theme_color_overlayFilling, R.id.theme_color_seekEmpty ->
      -14803426 // 0xff1e1e1e
    R.id.theme_color_fillingPressed ->
      -14671840 // 0xff202020
    R.id.theme_color_headerBarCallActive ->
      -12500671 // 0xff414141
    R.id.theme_color_headerBarCallIncoming ->
      -8355712 // 0xff808080
    R.id.theme_color_headerPlaceholder ->
      285212671 // 0x10ffffff
    R.id.theme_color_iconLight ->
      -11248797 // 0xff545b63
    R.id.theme_color_introSection ->
      -8289919 // 0xff818181
    R.id.theme_color_iv_blockQuote ->
      -197380 // 0xfffcfcfc
    R.id.theme_color_iv_pageSubtitle ->
      -4539718 // 0xffbababa
    R.id.theme_color_iv_pullQuote ->
      -394759 // 0xfff9f9f9
    R.id.theme_color_iv_separator ->
      -12303292 // 0xff444444
    R.id.theme_color_iv_textReferenceBackground ->
      720564978 // 0x2af2f2f2
    R.id.theme_color_iv_textReferenceBackgroundPressed ->
      820044000 // 0x30e0e0e0
    R.id.theme_color_iv_textReferenceOutline, R.id.theme_color_tooltip_outline ->
      1157627903 // 0x44ffffff
    R.id.theme_color_messageSelection ->
      721420287 // 0x2affffff
    R.id.theme_color_notificationSecure, R.id.theme_color_textSecure ->
      -8854914 // 0xff78e27e
    R.id.theme_color_placeholder ->
      218103807 // 0x0cffffff
    R.id.theme_color_playerButtonActive ->
      -3355444 // 0xffcccccc
    R.id.theme_color_playerCoverPlaceholder ->
      -15658735 // 0xff111111
    R.id.theme_color_previewBackground ->
      1879048192 // 0x70000000
    R.id.theme_color_seekDone ->
      -4144960 // 0xffc0c0c0
    R.id.theme_color_sliderInactive ->
      -13553359 // 0xff313131
    R.id.theme_color_textSelectionHighlight ->
      1442840575 // 0x55ffffff
    R.id.theme_color_snackbarUpdate ->
      -13750738 // 0xff2e2e2e
    R.id.theme_color_statusBar ->
      1073741824 // 0x40000000
    R.id.theme_color_togglerActiveBackground, R.id.theme_color_togglerPositiveBackground ->
      -7697782 // 0xff8a8a8a
    R.id.theme_color_togglerInactive ->
      -5723992 // 0xffa8a8a8
    else -> super.getColor(colorId)
  }
}