@file:JvmName("ThemeOrange")

package org.thunderdog.challegram.theme.builtin

import androidx.annotation.ColorInt
import me.vkryl.annotation.Autogenerated
import org.thunderdog.challegram.R
import org.thunderdog.challegram.theme.ThemeId
import org.thunderdog.challegram.theme.ThemeColorIdTinted
import org.thunderdog.challegram.theme.ThemeProperty

@Autogenerated class ThemeOrange : ThemeDefault(ThemeId.ORANGE) {
  override fun getProperty (@ThemeProperty propertyId: Int): Float = when (propertyId) {
    ThemeProperty.PARENT_THEME ->
      1.0f
    else -> super.getProperty(propertyId)
  }

  @ColorInt override fun getColor (@ThemeColorIdTinted colorId: Int): Int = when (colorId) {
    R.id.theme_color_badge, R.id.theme_color_bubbleIn_textLink, R.id.theme_color_bubbleOut_file, R.id.theme_color_bubbleOut_messageAuthor, R.id.theme_color_bubbleOut_textLink, R.id.theme_color_bubbleOut_ticks, R.id.theme_color_bubbleOut_ticksRead, R.id.theme_color_chatListAction, R.id.theme_color_chatSendButton, R.id.theme_color_circleButtonActive, R.id.theme_color_circleButtonRegular, R.id.theme_color_circleButtonTheme, R.id.theme_color_file, R.id.theme_color_headerBarCallActive, R.id.theme_color_iconActive, R.id.theme_color_iv_textLink, R.id.theme_color_iv_textMarkedLink, R.id.theme_color_messageAuthor, R.id.theme_color_online, R.id.theme_color_playerButtonActive, R.id.theme_color_snackbarUpdate, R.id.theme_color_textLink, R.id.theme_color_ticks, R.id.theme_color_ticksRead, R.id.theme_color_togglerActive ->
      -765666 // 0xfff4511e
    R.id.theme_color_bubbleIn_progress, R.id.theme_color_bubbleOut_inlineOutline, R.id.theme_color_bubbleOut_waveformActive, R.id.theme_color_checkActive, R.id.theme_color_inlineOutline, R.id.theme_color_inputActive, R.id.theme_color_profileSectionActiveContent, R.id.theme_color_progress, R.id.theme_color_textNeutral, R.id.theme_color_unreadText, R.id.theme_color_waveformActive ->
      -43230 // 0xffff5722
    R.id.theme_color_bubbleIn_textLinkPressHighlight, R.id.theme_color_bubbleOut_textLinkPressHighlight, R.id.theme_color_iv_textLinkPressHighlight, R.id.theme_color_iv_textMarkedLinkPressHighlight, R.id.theme_color_textLinkPressHighlight ->
      1089753374 // 0x40f4511e
    R.id.theme_color_bubbleOut_background ->
      -269600 // 0xfffbe2e0
    R.id.theme_color_bubbleOut_chatCorrectFilling, R.id.theme_color_bubbleOut_chatCorrectChosenFilling, R.id.theme_color_bubbleOut_chatVerticalLine, R.id.theme_color_chatListVerify, R.id.theme_color_controlActive, R.id.theme_color_messageSwipeBackground, R.id.theme_color_messageVerticalLine, R.id.theme_color_promo, R.id.theme_color_seekDone, R.id.theme_color_sliderActive, R.id.theme_color_textSearchQueryHighlight ->
      -36797 // 0xffff7043
    R.id.theme_color_bubbleOut_inlineIcon, R.id.theme_color_bubbleOut_inlineText, R.id.theme_color_inlineIcon, R.id.theme_color_inlineText, R.id.theme_color_profileSectionActive ->
      -1684967 // 0xffe64a19
    R.id.theme_color_bubbleOut_progress, R.id.theme_color_bubbleOut_separator, R.id.theme_color_bubbleOut_time ->
      -4222847 // 0xffbf9081
    R.id.theme_color_bubbleOut_waveformInactive, R.id.theme_color_textSelectionHighlight, R.id.theme_color_waveformInactive ->
      -13124 // 0xffffccbc
    R.id.theme_color_headerBackground, R.id.theme_color_notification, R.id.theme_color_notificationLink, R.id.theme_color_notificationPlayer, R.id.theme_color_passcode ->
      -2604267 // 0xffd84315
    R.id.theme_color_messageSelection ->
      285169442 // 0x10ff5722
    R.id.theme_color_seekReady ->
      -9264 // 0xffffdbd0
    R.id.theme_color_textNegative ->
      -1754827 // 0xffe53935
    R.id.theme_color_togglerActiveBackground ->
      -21615 // 0xffffab91
    R.id.theme_color_unread ->
      -267801 // 0xfffbe9e7
    else -> super.getColor(colorId)
  }
}