package me.vkryl.annotation;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/**
 * Date: 11/11/18
 * Author: default
 *
 * Autogenerated classes, methods, etc must not be modified directly, because all changes will be lost.
 */
@Retention(RetentionPolicy.SOURCE)
public @interface Autogenerated { }
