package org.thunderdog.challegram.theme;

import androidx.annotation.IntDef;

import org.thunderdog.challegram.R;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

import me.vkryl.annotation.Autogenerated;

/**
 * Date: 25/12/20
 * Author: default
 */
@Autogenerated
@Retention(RetentionPolicy.SOURCE)
@IntDef({
  R.id.theme_color_textLight,
  R.id.theme_color_textSecure,
  R.id.theme_color_background_icon,
  R.id.theme_color_icon,
  R.id.theme_color_iconActive,
  R.id.theme_color_iconLight,
  R.id.theme_color_iconPositive,
  R.id.theme_color_iconNegative,
  R.id.theme_color_inlineIcon,
  R.id.theme_color_playerCoverIcon,
  R.id.theme_color_avatar_content,
  R.id.theme_color_headerText,
  R.id.theme_color_headerIcon,
  R.id.theme_color_headerButtonIcon,
  R.id.theme_color_passcodeIcon,
  R.id.theme_color_ticks,
  R.id.theme_color_ticksRead,
  R.id.theme_color_chatListMute,
  R.id.theme_color_chatListIcon,
  R.id.theme_color_chatListVerify,
  R.id.theme_color_badgeText,
  R.id.theme_color_badgeFailedText,
  R.id.theme_color_badgeMuted,
  R.id.theme_color_badgeMutedText,
  R.id.theme_color_chatSendButton,
  R.id.theme_color_messageAuthor,
  R.id.theme_color_bubble_mediaTimeText,
  R.id.theme_color_bubble_mediaTimeText_noWallpaper,
  R.id.theme_color_bubble_mediaOverlayText,
  R.id.theme_color_bubbleIn_time,
  R.id.theme_color_bubbleOut_time,
  R.id.theme_color_bubbleOut_inlineIcon,
  R.id.theme_color_bubbleOut_waveformActive,
  R.id.theme_color_bubbleOut_file,
  R.id.theme_color_bubbleOut_ticks,
  R.id.theme_color_bubbleOut_ticksRead,
  R.id.theme_color_bubbleOut_messageAuthor,
  R.id.theme_color_file,
  R.id.theme_color_waveformActive,
  R.id.theme_color_waveformInactive,
  R.id.theme_color_white
})
public @interface PorterDuffThemeColorId { }