@file:JvmName("ThemeProperties")

package org.thunderdog.challegram.theme

import me.vkryl.annotation.Autogenerated

@Autogenerated class ThemeProperties {
  private var parentTheme: Float? = null
  private var wallpaperId: Float? = null
  private var dark: Float? = null
  private var imageCorner: Float? = null
  private var replaceShadowsWithSeparators: Float? = null
  private var bubbleCornerMerged: Float? = null
  private var bubbleCorner: Float? = null
  private var bubbleCornerLegacy: Float? = null
  private var bubbleOuterMargin: Float? = null
  private var bubbleOutline: Float? = null
  private var bubbleOutlineSize: Float? = null
  private var bubbleUnreadShadow: Float? = null
  private var bubbleDateCorner: Float? = null
  private var dateCorner: Float? = null
  private var wallpaperUsageId: Float? = null
  private var shadowDepth: Float? = null
  private var subtitleAlpha: Float? = null
  private var lightStatusBar: Float? = null
  private var wallpaperOverrideDate: Float? = null
  private var wallpaperOverrideUnread: Float? = null
  private var wallpaperOverrideMediaReply: Float? = null
  private var wallpaperOverrideTime: Float? = null
  private var wallpaperOverrideButton: Float? = null
  private var wallpaperOverrideOverlay: Float? = null
  
  constructor ()
  constructor (copy: ThemeProperties) {
    this.parentTheme = copy.parentTheme
    this.wallpaperId = copy.wallpaperId
    this.dark = copy.dark
    this.imageCorner = copy.imageCorner
    this.replaceShadowsWithSeparators = copy.replaceShadowsWithSeparators
    this.bubbleCornerMerged = copy.bubbleCornerMerged
    this.bubbleCorner = copy.bubbleCorner
    this.bubbleCornerLegacy = copy.bubbleCornerLegacy
    this.bubbleOuterMargin = copy.bubbleOuterMargin
    this.bubbleOutline = copy.bubbleOutline
    this.bubbleOutlineSize = copy.bubbleOutlineSize
    this.bubbleUnreadShadow = copy.bubbleUnreadShadow
    this.bubbleDateCorner = copy.bubbleDateCorner
    this.dateCorner = copy.dateCorner
    this.wallpaperUsageId = copy.wallpaperUsageId
    this.shadowDepth = copy.shadowDepth
    this.subtitleAlpha = copy.subtitleAlpha
    this.lightStatusBar = copy.lightStatusBar
    this.wallpaperOverrideDate = copy.wallpaperOverrideDate
    this.wallpaperOverrideUnread = copy.wallpaperOverrideUnread
    this.wallpaperOverrideMediaReply = copy.wallpaperOverrideMediaReply
    this.wallpaperOverrideTime = copy.wallpaperOverrideTime
    this.wallpaperOverrideButton = copy.wallpaperOverrideButton
    this.wallpaperOverrideOverlay = copy.wallpaperOverrideOverlay
  }

  fun get (@ThemeProperty propertyId: Int): Float? = when (propertyId) {
    ThemeProperty.PARENT_THEME -> this.parentTheme
    ThemeProperty.WALLPAPER_ID -> this.wallpaperId
    ThemeProperty.DARK -> this.dark
    ThemeProperty.IMAGE_CORNER -> this.imageCorner
    ThemeProperty.REPLACE_SHADOWS_WITH_SEPARATORS -> this.replaceShadowsWithSeparators
    ThemeProperty.BUBBLE_CORNER_MERGED -> this.bubbleCornerMerged
    ThemeProperty.BUBBLE_CORNER -> this.bubbleCorner
    ThemeProperty.BUBBLE_CORNER_LEGACY -> this.bubbleCornerLegacy
    ThemeProperty.BUBBLE_OUTER_MARGIN -> this.bubbleOuterMargin
    ThemeProperty.BUBBLE_OUTLINE -> this.bubbleOutline
    ThemeProperty.BUBBLE_OUTLINE_SIZE -> this.bubbleOutlineSize
    ThemeProperty.BUBBLE_UNREAD_SHADOW -> this.bubbleUnreadShadow
    ThemeProperty.BUBBLE_DATE_CORNER -> this.bubbleDateCorner
    ThemeProperty.DATE_CORNER -> this.dateCorner
    ThemeProperty.WALLPAPER_USAGE_ID -> this.wallpaperUsageId
    ThemeProperty.SHADOW_DEPTH -> this.shadowDepth
    ThemeProperty.SUBTITLE_ALPHA -> this.subtitleAlpha
    ThemeProperty.LIGHT_STATUS_BAR -> this.lightStatusBar
    ThemeProperty.WALLPAPER_OVERRIDE_DATE -> this.wallpaperOverrideDate
    ThemeProperty.WALLPAPER_OVERRIDE_UNREAD -> this.wallpaperOverrideUnread
    ThemeProperty.WALLPAPER_OVERRIDE_MEDIA_REPLY -> this.wallpaperOverrideMediaReply
    ThemeProperty.WALLPAPER_OVERRIDE_TIME -> this.wallpaperOverrideTime
    ThemeProperty.WALLPAPER_OVERRIDE_BUTTON -> this.wallpaperOverrideButton
    ThemeProperty.WALLPAPER_OVERRIDE_OVERLAY -> this.wallpaperOverrideOverlay
    else -> throw Theme.newError(propertyId, "propertyId")
  }

  fun set (@ThemeProperty propertyId: Int, value: Float?) = when (propertyId) {
    ThemeProperty.PARENT_THEME -> this.parentTheme = value
    ThemeProperty.WALLPAPER_ID -> this.wallpaperId = value
    ThemeProperty.DARK -> this.dark = value
    ThemeProperty.IMAGE_CORNER -> this.imageCorner = value
    ThemeProperty.REPLACE_SHADOWS_WITH_SEPARATORS -> this.replaceShadowsWithSeparators = value
    ThemeProperty.BUBBLE_CORNER_MERGED -> this.bubbleCornerMerged = value
    ThemeProperty.BUBBLE_CORNER -> this.bubbleCorner = value
    ThemeProperty.BUBBLE_CORNER_LEGACY -> this.bubbleCornerLegacy = value
    ThemeProperty.BUBBLE_OUTER_MARGIN -> this.bubbleOuterMargin = value
    ThemeProperty.BUBBLE_OUTLINE -> this.bubbleOutline = value
    ThemeProperty.BUBBLE_OUTLINE_SIZE -> this.bubbleOutlineSize = value
    ThemeProperty.BUBBLE_UNREAD_SHADOW -> this.bubbleUnreadShadow = value
    ThemeProperty.BUBBLE_DATE_CORNER -> this.bubbleDateCorner = value
    ThemeProperty.DATE_CORNER -> this.dateCorner = value
    ThemeProperty.WALLPAPER_USAGE_ID -> this.wallpaperUsageId = value
    ThemeProperty.SHADOW_DEPTH -> this.shadowDepth = value
    ThemeProperty.SUBTITLE_ALPHA -> this.subtitleAlpha = value
    ThemeProperty.LIGHT_STATUS_BAR -> this.lightStatusBar = value
    ThemeProperty.WALLPAPER_OVERRIDE_DATE -> this.wallpaperOverrideDate = value
    ThemeProperty.WALLPAPER_OVERRIDE_UNREAD -> this.wallpaperOverrideUnread = value
    ThemeProperty.WALLPAPER_OVERRIDE_MEDIA_REPLY -> this.wallpaperOverrideMediaReply = value
    ThemeProperty.WALLPAPER_OVERRIDE_TIME -> this.wallpaperOverrideTime = value
    ThemeProperty.WALLPAPER_OVERRIDE_BUTTON -> this.wallpaperOverrideButton = value
    ThemeProperty.WALLPAPER_OVERRIDE_OVERLAY -> this.wallpaperOverrideOverlay = value
    else -> throw Theme.newError(propertyId, "propertyId")
  }
  
  companion object {
    const val COUNT = 24

    @JvmStatic fun getAll (): Array<Int> = arrayOf(
      ThemeProperty.PARENT_THEME,
      ThemeProperty.WALLPAPER_ID,
      ThemeProperty.DARK,
      ThemeProperty.IMAGE_CORNER,
      ThemeProperty.REPLACE_SHADOWS_WITH_SEPARATORS,
      ThemeProperty.BUBBLE_CORNER_MERGED,
      ThemeProperty.BUBBLE_CORNER,
      ThemeProperty.BUBBLE_CORNER_LEGACY,
      ThemeProperty.BUBBLE_OUTER_MARGIN,
      ThemeProperty.BUBBLE_OUTLINE,
      ThemeProperty.BUBBLE_OUTLINE_SIZE,
      ThemeProperty.BUBBLE_UNREAD_SHADOW,
      ThemeProperty.BUBBLE_DATE_CORNER,
      ThemeProperty.DATE_CORNER,
      ThemeProperty.WALLPAPER_USAGE_ID,
      ThemeProperty.SHADOW_DEPTH,
      ThemeProperty.SUBTITLE_ALPHA,
      ThemeProperty.LIGHT_STATUS_BAR,
      ThemeProperty.WALLPAPER_OVERRIDE_DATE,
      ThemeProperty.WALLPAPER_OVERRIDE_UNREAD,
      ThemeProperty.WALLPAPER_OVERRIDE_MEDIA_REPLY,
      ThemeProperty.WALLPAPER_OVERRIDE_TIME,
      ThemeProperty.WALLPAPER_OVERRIDE_BUTTON,
      ThemeProperty.WALLPAPER_OVERRIDE_OVERLAY
    )

    @JvmStatic fun getMap (): Map<String, Int> = mapOf(
      Pair("parentTheme", ThemeProperty.PARENT_THEME),
      Pair("wallpaperId", ThemeProperty.WALLPAPER_ID),
      Pair("dark", ThemeProperty.DARK),
      Pair("imageCorner", ThemeProperty.IMAGE_CORNER),
      Pair("replaceShadowsWithSeparators", ThemeProperty.REPLACE_SHADOWS_WITH_SEPARATORS),
      Pair("bubbleCornerMerged", ThemeProperty.BUBBLE_CORNER_MERGED),
      Pair("bubbleCorner", ThemeProperty.BUBBLE_CORNER),
      Pair("bubbleCornerLegacy", ThemeProperty.BUBBLE_CORNER_LEGACY),
      Pair("bubbleOuterMargin", ThemeProperty.BUBBLE_OUTER_MARGIN),
      Pair("bubbleOutline", ThemeProperty.BUBBLE_OUTLINE),
      Pair("bubbleOutlineSize", ThemeProperty.BUBBLE_OUTLINE_SIZE),
      Pair("bubbleUnreadShadow", ThemeProperty.BUBBLE_UNREAD_SHADOW),
      Pair("bubbleDateCorner", ThemeProperty.BUBBLE_DATE_CORNER),
      Pair("dateCorner", ThemeProperty.DATE_CORNER),
      Pair("wallpaperUsageId", ThemeProperty.WALLPAPER_USAGE_ID),
      Pair("shadowDepth", ThemeProperty.SHADOW_DEPTH),
      Pair("subtitleAlpha", ThemeProperty.SUBTITLE_ALPHA),
      Pair("lightStatusBar", ThemeProperty.LIGHT_STATUS_BAR),
      Pair("wallpaperOverrideDate", ThemeProperty.WALLPAPER_OVERRIDE_DATE),
      Pair("wallpaperOverrideUnread", ThemeProperty.WALLPAPER_OVERRIDE_UNREAD),
      Pair("wallpaperOverrideMediaReply", ThemeProperty.WALLPAPER_OVERRIDE_MEDIA_REPLY),
      Pair("wallpaperOverrideTime", ThemeProperty.WALLPAPER_OVERRIDE_TIME),
      Pair("wallpaperOverrideButton", ThemeProperty.WALLPAPER_OVERRIDE_BUTTON),
      Pair("wallpaperOverrideOverlay", ThemeProperty.WALLPAPER_OVERRIDE_OVERLAY)
    )

    @JvmStatic fun getName (@ThemeProperty propertyId: Int): String = when (propertyId) {
      ThemeProperty.PARENT_THEME -> "parentTheme"
      ThemeProperty.WALLPAPER_ID -> "wallpaperId"
      ThemeProperty.DARK -> "dark"
      ThemeProperty.IMAGE_CORNER -> "imageCorner"
      ThemeProperty.REPLACE_SHADOWS_WITH_SEPARATORS -> "replaceShadowsWithSeparators"
      ThemeProperty.BUBBLE_CORNER_MERGED -> "bubbleCornerMerged"
      ThemeProperty.BUBBLE_CORNER -> "bubbleCorner"
      ThemeProperty.BUBBLE_CORNER_LEGACY -> "bubbleCornerLegacy"
      ThemeProperty.BUBBLE_OUTER_MARGIN -> "bubbleOuterMargin"
      ThemeProperty.BUBBLE_OUTLINE -> "bubbleOutline"
      ThemeProperty.BUBBLE_OUTLINE_SIZE -> "bubbleOutlineSize"
      ThemeProperty.BUBBLE_UNREAD_SHADOW -> "bubbleUnreadShadow"
      ThemeProperty.BUBBLE_DATE_CORNER -> "bubbleDateCorner"
      ThemeProperty.DATE_CORNER -> "dateCorner"
      ThemeProperty.WALLPAPER_USAGE_ID -> "wallpaperUsageId"
      ThemeProperty.SHADOW_DEPTH -> "shadowDepth"
      ThemeProperty.SUBTITLE_ALPHA -> "subtitleAlpha"
      ThemeProperty.LIGHT_STATUS_BAR -> "lightStatusBar"
      ThemeProperty.WALLPAPER_OVERRIDE_DATE -> "wallpaperOverrideDate"
      ThemeProperty.WALLPAPER_OVERRIDE_UNREAD -> "wallpaperOverrideUnread"
      ThemeProperty.WALLPAPER_OVERRIDE_MEDIA_REPLY -> "wallpaperOverrideMediaReply"
      ThemeProperty.WALLPAPER_OVERRIDE_TIME -> "wallpaperOverrideTime"
      ThemeProperty.WALLPAPER_OVERRIDE_BUTTON -> "wallpaperOverrideButton"
      ThemeProperty.WALLPAPER_OVERRIDE_OVERLAY -> "wallpaperOverrideOverlay"
      else -> throw Theme.newError(propertyId, "propertyId")
    }
  }
}