package org.thunderdog.challegram.theme;

import androidx.annotation.IntDef;

import org.thunderdog.challegram.R;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

import me.vkryl.annotation.Autogenerated;

/**
 * Date: 8/7/17
 * Author: default
 */
@Autogenerated
@Retention(RetentionPolicy.SOURCE)
@IntDef({
  R.id.theme_color_snackbarUpdate,
  R.id.theme_color_textSelectionHighlight,
  R.id.theme_color_textNeutral,
  R.id.theme_color_textLink,
  R.id.theme_color_textLinkPressHighlight,
  R.id.theme_color_textSearchQueryHighlight,
  R.id.theme_color_iconActive,
  R.id.theme_color_progress,
  R.id.theme_color_controlActive,
  R.id.theme_color_checkActive,
  R.id.theme_color_sliderActive,
  R.id.theme_color_togglerActive,
  R.id.theme_color_togglerActiveBackground,
  R.id.theme_color_inputActive,
  R.id.theme_color_inlineOutline,
  R.id.theme_color_inlineText,
  R.id.theme_color_inlineIcon,
  R.id.theme_color_circleButtonRegular,
  R.id.theme_color_circleButtonActive,
  R.id.theme_color_circleButtonTheme,
  R.id.theme_color_seekReady,
  R.id.theme_color_seekDone,
  R.id.theme_color_playerButtonActive,
  R.id.theme_color_online,
  R.id.theme_color_promo,
  R.id.theme_color_profileSectionActive,
  R.id.theme_color_profileSectionActiveContent,
  R.id.theme_color_headerBackground,
  R.id.theme_color_headerBarCallActive,
  R.id.theme_color_passcode,
  R.id.theme_color_notification,
  R.id.theme_color_notificationLink,
  R.id.theme_color_notificationPlayer,
  R.id.theme_color_ticks,
  R.id.theme_color_ticksRead,
  R.id.theme_color_chatListAction,
  R.id.theme_color_chatListVerify,
  R.id.theme_color_badge,
  R.id.theme_color_chatSendButton,
  R.id.theme_color_unread,
  R.id.theme_color_unreadText,
  R.id.theme_color_messageVerticalLine,
  R.id.theme_color_messageSelection,
  R.id.theme_color_messageSwipeBackground,
  R.id.theme_color_messageAuthor,
  R.id.theme_color_bubbleIn_progress,
  R.id.theme_color_bubbleIn_textLink,
  R.id.theme_color_bubbleIn_textLinkPressHighlight,
  R.id.theme_color_bubbleOut_background,
  R.id.theme_color_bubbleOut_time,
  R.id.theme_color_bubbleOut_progress,
  R.id.theme_color_bubbleOut_textLink,
  R.id.theme_color_bubbleOut_textLinkPressHighlight,
  R.id.theme_color_bubbleOut_separator,
  R.id.theme_color_bubbleOut_chatVerticalLine,
  R.id.theme_color_bubbleOut_chatCorrectFilling,
  R.id.theme_color_bubbleOut_chatCorrectChosenFilling,
  R.id.theme_color_bubbleOut_inlineText,
  R.id.theme_color_bubbleOut_inlineOutline,
  R.id.theme_color_bubbleOut_inlineIcon,
  R.id.theme_color_bubbleOut_waveformActive,
  R.id.theme_color_bubbleOut_waveformInactive,
  R.id.theme_color_bubbleOut_file,
  R.id.theme_color_bubbleOut_ticks,
  R.id.theme_color_bubbleOut_ticksRead,
  R.id.theme_color_bubbleOut_messageAuthor,
  R.id.theme_color_file,
  R.id.theme_color_waveformActive,
  R.id.theme_color_waveformInactive,
  R.id.theme_color_iv_textMarkedLink,
  R.id.theme_color_iv_textMarkedLinkPressHighlight,
  R.id.theme_color_iv_textLink,
  R.id.theme_color_iv_textLinkPressHighlight
})
public @interface ThemeColorIdTinted { }