package tgx.gradle.task

import groovy.util.Node
import groovy.util.NodeList
import groovy.xml.XmlParser
import org.gradle.api.DefaultTask
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.*
import tgx.gradle.data.Theme
import tgx.gradle.fatal
import tgx.gradle.validateDir
import java.io.Writer

@CacheableTask
abstract class GenerateThemesTask : DefaultTask() {
  @get:InputFile
  @get:PathSensitive(PathSensitivity.RELATIVE)
  abstract val colorsAndProperties: RegularFileProperty

  @get:InputFiles
  @get:PathSensitive(PathSensitivity.RELATIVE)
  abstract val themeFiles: ConfigurableFileCollection

  @get:OutputDirectory
  abstract val resOutputDir: DirectoryProperty

  @get:OutputDirectory
  abstract val javaOutputDir: DirectoryProperty

  @get:OutputDirectory
  abstract val kotlinOutputDir: DirectoryProperty

  @TaskAction
  fun generateThemes () {
    val java = validateDir(javaOutputDir.get().asFile)
    val kotlin = validateDir(kotlinOutputDir.get().asFile)
    val res = validateDir(resOutputDir.get().asFile)

    val themes = XmlParser().parse(colorsAndProperties.get().asFile)

    val generatedIds = ArrayList<String>()

    // Themes

    val themeColors = ArrayList<String>()
    val fallbackColors = mutableMapOf<String, String>()
    val themeProperties = ArrayList<String>()
    val tintedColors = mutableSetOf<String>()
    val porterDuffColors = mutableSetOf<String>()

    for (item in (((themes["sections"] as NodeList)[0] as Node)["item"]) as NodeList) {
      val name = (item as Node)["@name"].toString()
      generatedIds.add("theme_category_${name}")
    }
    for (item in (((themes["properties"] as NodeList)[0] as Node)["item"]) as NodeList) {
      val name = (item as Node)["@name"].toString()
      // generatedIds.add("theme_property_${name}")
      themeProperties.add(name)
    }
    for (item in (((themes["colors"] as NodeList)[0] as Node)["item"]) as NodeList) {
      val name = (item as Node)["@name"].toString()
      val tinted = item["@tinted"]?.toString() == "true"
      val needsPorterDuff = item["@porterDuff"]?.toString() == "true"
      val fallbackColorId = item["@fallback"]?.toString()
      // generatedIds.add("theme_color_${name}")
      themeColors.add(name)
      if (tinted) {
        tintedColors.add(name)
      }
      if (needsPorterDuff) {
        porterDuffColors.add(name)
      }
      if (!fallbackColorId.isNullOrEmpty()) {
        if (fallbackColors.containsKey(fallbackColorId) || name == fallbackColorId) {
          error("Recursive fallback: $name <-> $fallbackColorId")
        }
        fallbackColors[name] = fallbackColorId
      }
    }
    for (entry in fallbackColors.entries) {
      if (!themeColors.contains(entry.value)) {
        error("Unknown fallback color id: ${entry.key} -> ${entry.value}")
      }
    }
    val themeSettingsNode = (themes["settings"] as NodeList)[0] as Node
    val defaultThemeNode = (themeSettingsNode["default-theme"] as NodeList)[0] as Node
    val sourceTheme = ((themeSettingsNode["source-theme"] as NodeList)[0] as Node).toInteger()
    val defaultLightTheme = ((defaultThemeNode["light"] as NodeList)[0] as Node).toInteger()
    val defaultDarkTheme = ((defaultThemeNode["dark"] as NodeList)[0] as Node).toInteger()

    // generated.xml

    writeToFile(
      res.resolve("values/generated.xml")
    ) { xml ->
      xml.append("""
        <?xml version="1.0" encoding="utf-8"?>
        <!-- AUTOGENERATED, DO NOT MODIFY -->
        <resources xmlns:tools="http://schemas.android.com/tools" tools:ignore="MissingTranslation">
        
      """.trimIndent())
      generatedIds.forEach { id ->
        xml.append(
          "  <item type=\"id\" name=\"$id\" />\n"
        )
      }
      xml.append("""
        </resources>
      """.trimIndent())
    }

    // Themes

    val themesList = mutableListOf<Theme>()
    val themesMap = mutableMapOf<Int, Theme>()
    val missingMap = mutableMapOf<Int, Set<String>>()
    themeFiles.forEach { themeFile ->
      val theme = Theme(themeFile)

      val missingKeys = if (theme.isTinted) tintedColors.toMutableList() else ArrayList(themeColors)
      missingKeys.removeAll(theme.colorByName.keys.toList())
      missingKeys.removeAll(fallbackColors.entries.filter { !missingKeys.contains(it.value) }.map { it.key })
      if (missingKeys.isNotEmpty()) {
        missingMap[theme.id] = missingKeys.toSet()
      }

      themesMap[theme.id] = theme
      themesList.add(theme)
    }
    themesList.sortBy { it.id }
    var prevTheme: Theme? = null
    for (theme in themesList) {
      if (prevTheme != null && prevTheme.id + 1 != theme.id) {
        error("Missing gap in themes identifiers: ${prevTheme.id} .. ${theme.id}")
      }
      prevTheme = theme
    }

    if (!themesMap.containsKey(defaultLightTheme))
      error("Default light theme #${defaultLightTheme} is missing")
    if (!themesMap.containsKey(defaultDarkTheme))
      error("Default dark theme #${defaultDarkTheme} is missing")

    if (missingMap.isNotEmpty()) {
      val warn = StringBuilder()
      val fatal = StringBuilder()
      for (entry in missingMap) {
        val theme = themesMap[entry.key]!!
        val warning = "\"${theme.name}\" theme ${if (theme.isTinted) "(tinted) misses" else "does not define"} ${entry.value.size} color(s): ${entry.value}"
        val b = if (theme.isTinted || theme.parentTheme == 0) fatal else warn
        if (b.isNotEmpty())
          b.append("\n\n")
        b.append(warning)
      }
      if (warn.isNotEmpty())
        logger.info(warn.toString())
      if (fatal.isNotEmpty()) {
        error(fatal.toString())
      }
    }

    // ThemeId.java

    writeToFile(
      java.resolve("org/thunderdog/challegram/theme/ThemeId.java")
    ) { java ->
      java.append("""
        /*
         * This file is a part of Telegram X
         * Copyright © 2014 (tgx-android@pm.me)
         *
         * This program is free software: you can redistribute it and/or modify
         * it under the terms of the GNU General Public License as published by
         * the Free Software Foundation, either version 3 of the License, or
         * (at your option) any later version.
         *
         * You should have received a copy of the GNU General Public License
         * along with this program. If not, see <https://www.gnu.org/licenses/>.
         *
         * File initially created on 19/01/2017
         *
         * AUTOGENERATED. DO NOT MODIFY
         */
        package org.thunderdog.challegram.theme;

        import androidx.annotation.IntDef;
        
        import java.lang.annotation.Retention;
        import java.lang.annotation.RetentionPolicy;
        
        @Retention(RetentionPolicy.SOURCE)
        @IntDef({
          ThemeId.NONE,
          ThemeId.TEMPORARY,
          ThemeId.CUSTOM,
        
          ${themesList.joinToString(",\n          ") { "ThemeId.${it.idName}" }}
        })
        public @interface ThemeId {
          int NONE = 0;
          int TEMPORARY = -1;
          int CUSTOM = -2;
        
          ${themesList.joinToString("\n          ") { "int ${it.idName} = ${it.id};" }}
        
          int ID_MIN = ThemeId.${themesList[0].idName};
          int ID_MAX = ThemeId.${themesList[themesList.size - 1].idName};
          int COUNT = ID_MAX - ID_MIN + 1;
        }
      """.trimIndent())
    }

    // PropertyId.java

    writeToFile(
      java.resolve("org/thunderdog/challegram/theme/PropertyId.java")
    ) { java ->
      java.append("""
        /*
         * This file is a part of Telegram X
         * Copyright © 2014 (tgx-android@pm.me)
         *
         * This program is free software: you can redistribute it and/or modify
         * it under the terms of the GNU General Public License as published by
         * the Free Software Foundation, either version 3 of the License, or
         * (at your option) any later version.
         *
         * You should have received a copy of the GNU General Public License
         * along with this program. If not, see <https://www.gnu.org/licenses/>.
         *
         * File initially created on 04/11/2018
         *
         * AUTOGENERATED. DO NOT MODIFY
         */
        package org.thunderdog.challegram.theme;
        
        import androidx.annotation.IntDef;

        import java.lang.annotation.Retention;
        import java.lang.annotation.RetentionPolicy;

        import me.vkryl.annotation.Autogenerated;
        
        @Autogenerated
        @Retention(RetentionPolicy.SOURCE)
        @IntDef({
          PropertyId.NONE,
          ${themeProperties.joinToString(",\n          ") {
            "PropertyId.${it.camelCaseToUpperCase()}"
          }}
        })
        public @interface PropertyId {
          int
            NONE = 0,
            ${
              themeProperties.mapIndexed { index, propertyId ->
                "${propertyId.camelCaseToUpperCase()} = ${index + 1}"
              }.joinToString(",\n            ", postfix = ";")
            }
        }
      """.trimIndent())
    }

    // ColorId.java

    writeToFile(
      java.resolve("org/thunderdog/challegram/theme/ColorId.java")
    ) { java ->
      java.append("""
        /*
         * This file is a part of Telegram X
         * Copyright © 2014 (tgx-android@pm.me)
         *
         * This program is free software: you can redistribute it and/or modify
         * it under the terms of the GNU General Public License as published by
         * the Free Software Foundation, either version 3 of the License, or
         * (at your option) any later version.
         *
         * You should have received a copy of the GNU General Public License
         * along with this program. If not, see <https://www.gnu.org/licenses/>.
         *
         * File initially created on 19/01/2017
         *
         * AUTOGENERATED. DO NOT MODIFY
         */
        package org.thunderdog.challegram.theme;

        import androidx.annotation.IntDef;

        import java.lang.annotation.Retention;
        import java.lang.annotation.RetentionPolicy;

        import me.vkryl.annotation.Autogenerated;

        @Autogenerated
        @Retention(RetentionPolicy.SOURCE)
        @IntDef({
          ColorId.NONE,
          ${themeColors.joinToString(",\n          ") {
            "ColorId.$it"
          }}
        })
        public @interface ColorId {
          int
            NONE = 0,
            ${
              themeColors.mapIndexed { index, colorId ->
                "$colorId = ${index + 1}"
              }.joinToString(",\n            ", postfix = ";")
            }
        }
      """.trimIndent())
    }

    // ColorIdTinted.java

    writeToFile(
      java.resolve("org/thunderdog/challegram/theme/ColorIdTinted.java")
    ) { java ->
      java.append("""
        /*
         * This file is a part of Telegram X
         * Copyright © 2014 (tgx-android@pm.me)
         *
         * This program is free software: you can redistribute it and/or modify
         * it under the terms of the GNU General Public License as published by
         * the Free Software Foundation, either version 3 of the License, or
         * (at your option) any later version.
         *
         * You should have received a copy of the GNU General Public License
         * along with this program. If not, see <https://www.gnu.org/licenses/>.
         *
         * File initially created on 08/07/2017
         *
         * AUTOGENERATED. DO NOT MODIFY
         */
        package org.thunderdog.challegram.theme;

        import androidx.annotation.IntDef;

        import org.thunderdog.challegram.R;

        import java.lang.annotation.Retention;
        import java.lang.annotation.RetentionPolicy;

        import me.vkryl.annotation.Autogenerated;

        @Autogenerated
        @Retention(RetentionPolicy.SOURCE)
        @IntDef({
          ColorId.NONE,
          ${tintedColors.joinToString(",\n          ") {
            "ColorId.$it"
          }}
        })
        public @interface ColorIdTinted { }
      """.trimIndent())
    }
    writeToFile(
      java.resolve("org/thunderdog/challegram/theme/PorterDuffColorId.java")
    ) { java ->
      java.append("""
        /*
         * This file is a part of Telegram X
         * Copyright © 2014 (tgx-android@pm.me)
         *
         * This program is free software: you can redistribute it and/or modify
         * it under the terms of the GNU General Public License as published by
         * the Free Software Foundation, either version 3 of the License, or
         * (at your option) any later version.
         *
         * You should have received a copy of the GNU General Public License
         * along with this program. If not, see <https://www.gnu.org/licenses/>.
         *
         * File initially created on 25/12/2020
         *
         * AUTOGENERATED. DO NOT MODIFY
         */
        package org.thunderdog.challegram.theme;

        import androidx.annotation.IntDef;

        import java.lang.annotation.Retention;
        import java.lang.annotation.RetentionPolicy;

        import me.vkryl.annotation.Autogenerated;

        @Autogenerated
        @Retention(RetentionPolicy.SOURCE)
        @IntDef({
          ColorId.NONE,
          ${porterDuffColors.joinToString(",\n          ") {
            "ColorId.$it"
          }}
        })
        public @interface PorterDuffColorId { }
      """.trimIndent())
    }
    writeToFile(
      kotlin.resolve("org/thunderdog/challegram/theme/FallbackColorId.kt")
    ) { kt ->
      kt.append("""
        @file:JvmName("FallbackColorId")
        
        package org.thunderdog.challegram.theme
        ${if (fallbackColors.isEmpty()) "\n        @Suppress(\"unused_parameter\")" else ""}
        @JvmName("get") fun getFallbackColorId (@ColorId colorId: Int): Int = ${if (fallbackColors.isEmpty()) "ColorId.NONE" else """when (colorId) {
          ${fallbackColors.entries.joinToString("\n          ") { "ColorId.${it.key} -> ColorId.${it.value}" }}
          else -> ColorId.NONE
        } 
        """}
      """.trimIndent())
    }
    writeToFile(
      kotlin.resolve("org/thunderdog/challegram/tool/PorterDuffPaint.kt")
    ) { kt ->
      kt.append("""
        @file:JvmName("PorterDuffPaint")

        package org.thunderdog.challegram.tool
        
        import android.graphics.Paint
        import android.graphics.PorterDuff
        import android.graphics.PorterDuffColorFilter
        import me.vkryl.core.alphaColor
        import org.thunderdog.challegram.core.Lang
        import org.thunderdog.challegram.theme.ColorId
        import org.thunderdog.challegram.theme.PorterDuffColorId
        import org.thunderdog.challegram.theme.Theme
        
        private fun Paint?.changePorterDuff (color: Int): Paint {
          if (this != null && this.color == color)
            return this
          val result = this ?: Paint(Paint.ANTI_ALIAS_FLAG or Paint.DITHER_FLAG or Paint.FILTER_BITMAP_FLAG)
          result.colorFilter = PorterDuffColorFilter(color, PorterDuff.Mode.SRC_IN)
          result.color = color
          return result
        }
        
        @JvmName("get") @JvmOverloads fun getPorterDuffPaint (@PorterDuffColorId colorId: Int, alpha: Float = 1.0f): Paint {
          val color = if (alpha != 1.0f) {
            alphaColor(alpha, Theme.getColor(colorId))
          } else {
            Theme.getColor(colorId)
          }
          return when (colorId) {
            ${porterDuffColors.joinToString("\n            ") { "ColorId.$it -> if (paint_$it != null) { paint_$it.changePorterDuff(color) } else { paint_$it = paint_$it.changePorterDuff(color); paint_$it!! }" }}
            else -> throw IllegalArgumentException(Integer.toString(colorId))
          }
        }
        
        ${porterDuffColors.joinToString("\n        ") { "private var paint_$it: Paint? = null" }}
      """.trimIndent())
    }

    // ThemeProperties.kt

    writeToFile(
      kotlin.resolve("org/thunderdog/challegram/theme/ThemeProperties.kt")
    ) { kt ->
      kt.append("""
        @file:JvmName("ThemeProperties")
        
        package org.thunderdog.challegram.theme
        
        import me.vkryl.annotation.Autogenerated
        
        @Autogenerated class ThemeProperties {
          ${themeProperties.joinToString("\n          ") { "private var $it: Float? = null" } }
          
          constructor ()
          constructor (copy: ThemeProperties) {
            ${themeProperties.joinToString("\n            ") { "this.$it = copy.$it" }}
          }
        
          fun get (@PropertyId propertyId: Int): Float? = when (propertyId) {
            ${themeProperties.joinToString("\n            ") { "PropertyId.${it.camelCaseToUpperCase()} -> this.$it" }}
            else -> throw Theme.newError(propertyId, "propertyId")
          }
        
          fun set (@PropertyId propertyId: Int, value: Float?) = when (propertyId) {
            ${themeProperties.joinToString("\n            ") { "PropertyId.${it.camelCaseToUpperCase()} -> this.$it = value" }}
            else -> throw Theme.newError(propertyId, "propertyId")
          }
          
          companion object {
            const val COUNT = ${themeProperties.size}
        
            @JvmStatic fun getAll (): Array<Int> = arrayOf(
              ${themeProperties.joinToString(",\n              ") { "PropertyId.${it.camelCaseToUpperCase()}" }}
            )
        
            @JvmStatic fun getMap (): Map<String, Int> = mapOf(
              ${themeProperties.joinToString(",\n              ") { "Pair(\"$it\", PropertyId.${it.camelCaseToUpperCase()})" } }
            )
        
            @JvmStatic fun getName (@PropertyId propertyId: Int): String = when (propertyId) {
              ${themeProperties.joinToString("\n              ") { "PropertyId.${it.camelCaseToUpperCase()} -> \"$it\"" } }
              else -> throw Theme.newError(propertyId, "propertyId")
            }
          }
        }
      """.trimIndent())
    }

    // ThemeColors.kt

    writeToFile(
      kotlin.resolve("org/thunderdog/challegram/theme/ThemeColors.kt")
    ) { kt ->
      kt.append("""
        @file:JvmName("ThemeColors")
        
        package org.thunderdog.challegram.theme
        
        import me.vkryl.annotation.Autogenerated
        
        @Autogenerated class ThemeColors {
          ${themeColors.joinToString("\n          ") { "private var $it: Int? = null" }}
        
          constructor ()
          constructor (copy: ThemeColors) {
            ${themeColors.joinToString("\n            ") { "this.$it = copy.$it" }}
          }
        
          fun get (@ColorId colorId: Int): Int? = when (colorId) {
            ${themeColors.joinToString("\n            ") { "ColorId.$it -> this.$it" }}
            ColorId.NONE -> null
            else -> throw Theme.newError(colorId, "colorId")
          }
        
          fun set (@ColorId colorId: Int, value: Int?) = when (colorId) {
            ${themeColors.joinToString("\n            ") { "ColorId.$it -> this.$it = value" }}
            else -> throw Theme.newError(colorId, "colorId")
          }
          
          companion object {
            const val COUNT = ${themeColors.size}
        
            @JvmStatic fun getAll (): MutableSet<Int> = mutableSetOf(
              ${themeColors.joinToString(",\n              ") {
                "ColorId.$it"
              }}
            )
        
            @JvmStatic fun getMap (): Map<String, Int> = mapOf(
              ${themeColors.joinToString(",\n              ") { "Pair(\"$it\", ${
                "ColorId.$it"
              })" }}
            )
        
            @JvmStatic fun getName (@ColorId colorId: Int): String = when (colorId) {
              ${themeColors.joinToString("\n              ") { "${
                "ColorId.$it"
              } -> \"$it\""} }
              else -> throw Theme.newError(colorId, "colorId")
            }
        
            @JvmStatic fun getNames (): Set<String> = setOf(
              ${themeColors.joinToString(",\n              ") { "\"$it\"" }}
            )
          }
        }
      """.trimIndent())
    }

    // Themes

    val rudimentaryFileNames = kotlin.resolve(
      "org/thunderdog/challegram/theme/builtin"
    ).takeIf {
      it.exists()
    }?.listFiles()?.map {
      it.name
    }?.toMutableSet() ?: mutableSetOf()

    val writeToThemeFile: (String, block: (Writer) -> Unit) -> Unit = { fileName, block ->
      writeToFile(
        kotlin.resolve("org/thunderdog/challegram/theme/builtin/${fileName}")
      ) {
        block(it)
      }
      rudimentaryFileNames -= fileName
    }

    writeToThemeFile(
      "ThemeBubbleOverride.kt"
    ) { kt ->
      kt.append("""
        @file:JvmName("ThemeBubbleOverride")
        
        package org.thunderdog.challegram.theme.builtin
        
        import androidx.annotation.ColorInt
        import me.vkryl.annotation.Autogenerated
        import org.thunderdog.challegram.theme.ColorId
        import org.thunderdog.challegram.theme.ThemeDelegate
        import org.thunderdog.challegram.theme.ThemeId
        import org.thunderdog.challegram.theme.ThemeSet
        
        @Autogenerated open class ThemeBubbleOverride (@ThemeId id: Int, @ThemeId bubbleThemeId: Int) : ThemeDefault(id) {
          private val bubbleTheme: ThemeDelegate = ThemeSet.getBuiltinTheme(bubbleThemeId)
          
          @ColorInt override fun getColor (colorId: Int) = when (colorId) {
            ${themeColors.filter { it.startsWith("bubbleOut_") }.joinToString(",\n            ") {
              "ColorId.$it"
            }} -> bubbleTheme.getColor(colorId)
            else -> super.getColor(colorId)
          }
        }
      """.trimIndent())
    }

    for (entry in themesMap) {
      val theme = entry.value
      val isSource = theme.id == sourceTheme
      val className = if (isSource) "Default" else theme.className
      val parentTheme = if (theme.parentTheme != 0) themesMap[theme.parentTheme] else if (!isSource) themesMap[sourceTheme] else null

      writeToThemeFile(
        "Theme${className}.kt"
      ) { writer ->
        writer.append("""
          @file:JvmName("Theme${className}")
          
          package org.thunderdog.challegram.theme.builtin
          
          """.trimIndent())

        if (theme.colorByName.isNotEmpty()) writer.append("\nimport androidx.annotation.ColorInt")

        writer.append("\nimport me.vkryl.annotation.Autogenerated")
        if (theme.colorByName.isNotEmpty()) {
          writer.append("\nimport org.thunderdog.challegram.theme.ColorId")
          if (theme.isTinted) {
            writer.append("\nimport org.thunderdog.challegram.theme.ColorIdTinted")
          }
        }
        writer.append("\nimport org.thunderdog.challegram.theme.ThemeId")
        if (theme.propertyByName.isNotEmpty()) {
          writer.append("\nimport org.thunderdog.challegram.theme.PropertyId")
        }
        writer.append("\n")

        writer.append(when {
          isSource -> """
            import org.thunderdog.challegram.theme.ThemeObject
            import org.thunderdog.challegram.theme.getFallbackColorId
            
            @Autogenerated open class Theme$className (@ThemeId id: Int = ThemeId.${theme.idName}) : ThemeObject(id)
          """.trimIndent()
          theme.bubbleTheme != 0 -> """
            
            @Autogenerated class Theme$className : ThemeBubbleOverride(ThemeId.${theme.idName}, ThemeId.${themesMap[theme.bubbleTheme]!!.idName})
          """.trimIndent()
          parentTheme!!.id == sourceTheme -> """
            
            @Autogenerated class Theme$className : ThemeDefault(ThemeId.${theme.idName})
          """.trimIndent()
          else -> """
            import org.thunderdog.challegram.theme.ThemeInherited
            
            @Autogenerated class Theme$className : ThemeInherited(ThemeId.${theme.idName}, ThemeId.${themesMap[theme.parentTheme]!!.idName})
          """.trimIndent()
        })

        var open = false

        var first = true
        for (property in theme.namesByProperty) {
          val names: MutableSet<String>
          if (parentTheme != null) {
            names = mutableSetOf()
            for (name in property.value) {
              if (property.key != parentTheme.effectiveProperty(name, themesMap, sourceTheme)) {
                names.add(name)
              }
            }
          } else {
            names = property.value
          }
          if (names.isEmpty())
            continue
          if (first) {
            if (!open) {
              writer.append(" {")
              open = true
            }
            writer.append("\n  override fun getProperty (@PropertyId propertyId: Int): Float = when (propertyId) {\n")
            first = false
          }
          writer.append(names.joinToString(", ", "    ", " ->\n      ") { "PropertyId.${it.camelCaseToUpperCase()}" })
            .append(property.key.toString())
            .append("f\n")
        }
        if (!first) {
          writer.append("    else -> super.getProperty(propertyId)\n")
                .append("  }\n")
        }

        first = true
        for (color in theme.namesByColor) {
          val names: MutableSet<String>
          if (parentTheme != null) {
            names = mutableSetOf()
            for (name in color.value) {
              if (color.key != parentTheme.effectiveColor(name, themesMap, sourceTheme)) {
                if (!themeColors.contains(name))
                  error("Unknown color id ${name} in ${theme.name} theme")
                names.add(name)
              }
            }
          } else {
            names = color.value
          }
          if (names.isEmpty())
            continue
          if (first) {
            if (!open) {
              writer.append(" {")
              open = true
            }
            writer.append("\n  @ColorInt override fun getColor (@${if (theme.isTinted) "ColorIdTinted" else "ColorId"} colorId: Int): Int = when (colorId) {\n")
            first = false
          }
          writer.append(names.joinToString(", ", "    ", " ->\n      ") {
            "ColorId.$it"
          }).append(Integer.parseUnsignedInt(color.key, 16).toString(10)).append(" // 0x${color.key}")
            .append("\n")
        }
        if (!first) {
          if (isSource) {
            writer.append("    else -> {\n" +
              "      val fallbackColorId = getFallbackColorId(colorId)\n" +
              "      if (fallbackColorId != ColorId.NONE) {\n" +
              "        getColor(fallbackColorId)\n" +
              "      } else {\n" +
              "        error(colorId)\n" +
              "      }\n" +
              "    }\n")
          } else {
            writer.append("    else -> super.getColor(colorId)\n")
          }
          writer.append("  }\n")
        }
        if (open) {
          writer.append("}")
        }
      }
    }

    if (rudimentaryFileNames.isNotEmpty()) {
      rudimentaryFileNames.forEach { fileName ->
        val rudimentaryFile = kotlin.resolve("org/thunderdog/challegram/theme/builtin/${fileName}")
        if (!rudimentaryFile.delete()) {
          fatal("Unable to delete rudimentary theme file: ${rudimentaryFile.absolutePath}")
        }
      }
    }
  }
}