package tgx.gradle.task

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.*
import tgx.gradle.config.tdlibEqualTypes
import tgx.gradle.data.ArrayType
import tgx.gradle.data.TdlibType
import tgx.gradle.validateDir
import java.util.zip.CRC32

@CacheableTask
abstract class GenerateTdlibFunctionsTask : DefaultTask() {
  @get:InputFile
  @get:PathSensitive(PathSensitivity.RELATIVE)
  abstract val tdApi: RegularFileProperty

  @get:OutputDirectory
  abstract val kotlinOutputDir: DirectoryProperty

  @TaskAction
  fun generateTdlibFunctions() {
    // TdCompileAssert.kt & TdUnsupported.kt
    val kotlin = validateDir(kotlinOutputDir.get().asFile)

    val tdApi = tdApi.get().asFile.readText()

    val tdTypesMap = mutableMapOf<String, Set<String>>()
    val tdTypeHashCode = mutableMapOf<String, String>()

    val typesRegex = Regex("public abstract static class ([a-zA-Z]+) extends Object \\{[^@]+[^\\n]+\\s+@IntDef\\(\\{([^}]+)")
    var matchResult: MatchResult?
    matchResult = typesRegex.find(tdApi)
    val tdTypes = mutableListOf<Pair<String, Pair<Set<String>, String>>>()
    val hashCodes = mutableSetOf<String>()
    while (matchResult != null) {
      val (typeName, constructorsRaw) = matchResult.destructured
      val constructorsOriginal = constructorsRaw.split(",").map {
        it.trim().replace(".CONSTRUCTOR", "")
      }.toSortedSet()
      val constructors = constructorsOriginal.map {
        it.replace(Regex("^${typeName}"), "")
      }.toSortedSet()
      val hashSrc = "${typeName}_${constructors.joinToString("_")}"
      val crc32 = CRC32()
      crc32.update(hashSrc.toByteArray())

      val hashCode = crc32.value.toHexString().replace(Regex("^0+"), "")
      if (!hashCodes.add(hashCode))
        error("hashCode collision for ${typeName}")
      val stubMethodName = "assert${typeName}_${hashCode}";
      if (stubMethodName.length > 65535) {
        error("Too long (${stubMethodName.length}) method name for type: ${typeName}")
      }
      tdTypes.add(Pair(typeName, Pair(constructors, stubMethodName)))
      tdTypesMap[typeName] = constructorsOriginal
      tdTypeHashCode[typeName] = hashCode

      matchResult = matchResult.next()
    }
    tdTypes.sortBy { it.first }

    writeToFile(kotlin.resolve(
      "tgx/td/TdCompileAssert.kt"
    )) { kt ->
      kt.append("""
        /*
         * This file is a part of tdlib-utils
         * Copyright © 2014 (tgx-android@pm.me)
         *
         * Licensed under the Apache License, Version 2.0 (the "License");
         * you may not use this file except in compliance with the License.
         * You may obtain a copy of the License at
         *
         *      http://www.apache.org/licenses/LICENSE-2.0
         *
         * Unless required by applicable law or agreed to in writing, software
         * distributed under the License is distributed on an "AS IS" BASIS,
         * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
         * See the License for the specific language governing permissions and
         * limitations under the License.
         */

        @file:JvmName("Td")
        @file:JvmMultifileClass

        package tgx.td

        import me.vkryl.annotation.Autogenerated
        import org.drinkless.tdlib.TdApi.*
        
        // Cause compilation error whenever new constructor is added to the TDLib type
        // by calling one of the corresponding stub methods below in places, where you expect to support all of them.
        
        ${tdTypes.joinToString("\n\n        ") {
          "${it.second.first.joinToString("\n        ") { const -> "// $const" } }\n        @Autogenerated fun ${it.second.second} (): ${it.first}? = null"
        }}
      """.trimIndent())
    }

    writeToFile(
      kotlin.resolve("tgx/td/TdUnsupported.kt")
    ) { kt ->
      kt.append("""
        /*
         * This file is a part of tdlib-utils
         * Copyright © 2014 (tgx-android@pm.me)
         *
         * Licensed under the Apache License, Version 2.0 (the "License");
         * you may not use this file except in compliance with the License.
         * You may obtain a copy of the License at
         *
         *      http://www.apache.org/licenses/LICENSE-2.0
         *
         * Unless required by applicable law or agreed to in writing, software
         * distributed under the License is distributed on an "AS IS" BASIS,
         * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
         * See the License for the specific language governing permissions and
         * limitations under the License.
         */

        @file:JvmName("Td")
        @file:JvmMultifileClass

        package tgx.td

        import me.vkryl.annotation.Autogenerated
        import org.drinkless.tdlib.TdApi.*
        
        // Use throw unsupported(object) to group multiple crashes of the same kind into one report,
        // and access critical places via Find Usages for the methods below when any new constructors are added

        ${tdTypes.joinToString("\n        ") {
          "@Autogenerated fun unsupported (data: ${it.first}): NotImplementedError = NotImplementedError(data.toString())"
        }}
      """.trimIndent())
    }

    val equalTypes = tdlibEqualTypes()
      .sortedWith(compareBy<TdlibType> {
        tdTypesMap.containsKey(it.name)
      }.thenBy {
        it.name
      })

    val arrayEqualTypes = equalTypes.filter {
      it.array != ArrayType.NONE
    }

    val fetchFieldsTypes = mutableListOf<String>()
    equalTypes.forEach { type ->
      val allConstructors = tdTypesMap[type.name]
      if (allConstructors != null) {
        fetchFieldsTypes.addAll(allConstructors)
      } else {
        fetchFieldsTypes.add(type.name)
      }
    }
    val tdTypeFields = mutableMapOf<String, List<Pair<String, String>>>()
    val fieldsRegex = Regex("public (${fetchFieldsTypes.joinToString("|")})\\(([^)]+)\\)")
    matchResult = fieldsRegex.find(tdApi)
    while (matchResult != null) {
      val (typeName, fieldsListRaw) = matchResult.destructured
      val fieldsList = fieldsListRaw.split(", ").map {
        val data = it.split(" ")
        Pair(data[0], data[1])
      }
      tdTypeFields[typeName] = fieldsList
      matchResult = matchResult.next()
    }

    fun tdCompare (type: String, a: String, b: String): String = when (type) {
      "int",
      "long",
      "float",
      "double",
      "byte",
      "boolean" -> "$a == $b"
      "int[]",
      "long[]",
      "double[]",
      "float[]",
      "byte[]",
      "boolean[]" -> "$a.contentEqualsOrEmpty($b)"
      "String" -> "$a.equalsOrEmpty($b)"
      "String[]" -> "$a.contentEqualsOrEmpty($b)"
      else -> "$a.equalsTo($b)"
    }

    fun typeEfficiencyOrder (type: String) = when (type) {
      "int",
      "long",
      "float",
      "double",
      "byte",
      "boolean" -> 1
      "String" -> 2
      "int[]",
      "long[]",
      "double[]",
      "float[]",
      "byte[]",
      "boolean[]" -> 3
      "String[]" -> 4
      else -> 2
    }

    fun fieldId (constructor: String, field: String) = "$constructor.$field"

    fun genConstructorCompare (type: TdlibType, constructor: String, indent: String): String {
      return (tdTypeFields[constructor].let { fields ->
        (if (!fields.isNullOrEmpty()) {
          "if (COMPILE_CHECK) {" +
            "\n${indent}  $constructor(" +
            "\n${indent}    ${tdTypeFields[constructor]!!.joinToString(",\n${indent}    ") {
              "this.${it.second}"
            } }" +
            "\n${indent}  )" +
            "\n${indent}}"
        } else "") +
          (fields?.filter {
            field -> !type.ignoredFields.contains(fieldId(constructor, field.second))
          }?.takeIf { it.isNotEmpty() }?.sortedWith(compareBy {
            typeEfficiencyOrder(it.first)
          })?.joinToString(separator = " &&\n${indent}", prefix = "\n${indent}") {
            tdCompare(it.first, "this.${it.second}", "b.${it.second}")
          } ?: "") +
          (fields?.filter {
            field -> type.ignoredFields.contains(fieldId(constructor, field.second))
          }?.takeIf { it.isNotEmpty() }?.joinToString(separator = "\n${indent}", prefix = "\n${indent}") {
            "// ignored: " + tdCompare(it.first, "this.${it.second}", "b.${it.second}")
          } ?: "") +
          ("\n${indent}true // nothing to compare".takeIf {
            fields == null || fields.count { field -> !type.ignoredFields.contains(fieldId(constructor, field.second)) } == 0
          } ?: "")
      })
    }

    writeToFile(
      kotlin.resolve("tgx/td/TdEqualsTo.kt")
    ) { kt ->
      kt.append("""
        /*
         * This file is a part of tdlib-utils
         * Copyright © 2014 (tgx-android@pm.me)
         *
         * Licensed under the Apache License, Version 2.0 (the "License");
         * you may not use this file except in compliance with the License.
         * You may obtain a copy of the License at
         *
         *      http://www.apache.org/licenses/LICENSE-2.0
         *
         * Unless required by applicable law or agreed to in writing, software
         * distributed under the License is distributed on an "AS IS" BASIS,
         * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
         * See the License for the specific language governing permissions and
         * limitations under the License.
         */

        @file:JvmName("Td")
        @file:JvmMultifileClass

        package tgx.td

        import me.vkryl.annotation.Autogenerated
        import org.drinkless.tdlib.TdApi.*
        import kotlin.contracts.ExperimentalContracts
        
        ${equalTypes.joinToString("\n        ") { type ->
          (if (type.isExperimental) "@OptIn(ExperimentalContracts::class)\n        " else "") +
          "@Autogenerated\n        fun ${type.name}?.equalsTo(other: ${type.name}?): Boolean = this.safeEqualsTo(other) { ${
            type.name.let {
              val maxFieldsCount = (tdTypesMap[type.name]?.map { constructor ->
                tdTypeFields[constructor]?.size ?: 0
              })?.max() ?: tdTypeFields[type.name]?.size ?: 0
              if (maxFieldsCount > 0) {
                "b"
              } else {
                "_" // unused variable
              }
            }
          } ->\n          " +
            (if (tdTypesMap.containsKey(type.name)) {
              "when (this.constructor) {\n          " +
                (tdTypesMap[type.name]!!.filter { constructor ->
                  tdTypeFields[constructor].isNullOrEmpty()
                }.takeIf { it.isNotEmpty() }?.joinToString(separator = ",\n          ", postfix = " ->\n              true // nothing to compare\n          ") { constructor ->
                  "  $constructor.CONSTRUCTOR"
                } ?: "") +
                (tdTypesMap[type.name]!!.filter { constructor ->
                  !tdTypeFields[constructor].isNullOrEmpty()
                }.takeIf { it.isNotEmpty() }?.joinToString(separator = "\n          ", postfix = "\n          ") { constructor ->
                  "  $constructor.CONSTRUCTOR -> {\n            " +
                    "  require(this is $constructor && b is $constructor)\n              " +
                    genConstructorCompare(type, constructor, indent = "              ") + "\n            " +
                  "}"
                } ?: "") + 
                "  else -> {\n            " +
                "  assert${type.name}_${tdTypeHashCode[type.name]}()\n            " +
                "  throw unsupported(this)" +
                "\n            }\n          }"
            } else genConstructorCompare(type, type.name, indent = "          ")) + "\n        " +
          "}\n      " + if (type.array == ArrayType.NONE) "" else {
            "\n        " +
            "@Autogenerated\n        " +
            "fun Array<${type.name}>?.equalsTo(other: Array<${type.name}>?): Boolean = \n        " +
            "  this.contentEqualsOrEmpty(other, ${type.name}::equalsTo)" + if (type.array == ArrayType.TWO_DIMENSIONAL) {
            "\n        " +
                "@Autogenerated\n        " +
                "fun Array<Array<${type.name}>>?.equalsTo(other: Array<Array<${type.name}>>?): Boolean = \n        " +
                "  this.contentEqualsOrEmpty(other, Array<${type.name}>::equalsTo)"
            } else ""
          }
        }}
      """.trimIndent())
    }
  }
}