#!/usr/bin/env python3
"""Generate the bounded, reflection-free article snapshot codec from pinned TdApi.java.

Run from any directory. The generated source is checked in, so Python is not a
build/runtime dependency. Only the transitive closure of the roots below is used.
"""
import hashlib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "tdlib/src/main/java/org/drinkless/tdlib/TdApi.java"
DEST = ROOT / "app/src/main/java/org/thunderdog/challegram/data/article/ArticleCodec.java"
text = SOURCE.read_text(encoding="utf-8")
classes = {}
matches = list(re.finditer(r"^    public (?:abstract )?static class (\w+)(?:<[^\n]+?>)? extends ([\w<>]+) \{", text, re.M))
for i, match in enumerate(matches):
    body = text[match.end():matches[i + 1].start() if i + 1 < len(matches) else len(text)]
    fields = re.findall(r"^        (?:@\w+\s+)*public (?:@\w+\s+)*([\w\[\]]+) (\w+);$", body, re.M)
    constructors = re.findall(r"^        public " + match[1] + r"\(([^)]*)\)", body, re.M)
    expected = max((len(c.split(",")) if c.strip() else 0 for c in constructors), default=0)
    if expected != len(fields):
        raise ValueError(f"Field/constructor mismatch in {match[1]}: {len(fields)} != {expected}")
    classes[match[1]] = (match[2], fields, "abstract" in match[0])

primitive = {"boolean": "Boolean", "int": "Int", "long": "Long", "double": "Double", "byte": "Byte"}
pending = ["RichMessage", "InputRichMessage"]
selected = set()
while pending:
    name = pending.pop().replace("[]", "")
    if name in primitive or name == "String" or name in selected:
        continue
    if name not in classes:
        raise ValueError("Unknown type: " + name)
    selected.add(name)
    base, fields, abstract = classes[name]
    if abstract:
        # User-account articles use structured blocks. Including bot-only text
        # sources would pull the entire InputMessageContent API into this codec.
        pending.extend(["RichMessageSourceBlocks"] if name == "RichMessageSource" else
                       (n for n, (b, _, _) in classes.items() if b == name))
    else:
        pending.extend(t for t, _ in fields)
concrete = sorted(n for n in selected if not classes[n][2])
schema = "\n".join(n + repr(classes[n][1]) for n in concrete)
schema_hash = hashlib.sha256(schema.encode()).hexdigest()

header = '''/*
 * This file is a part of Telegram X.
 * SPDX-License-Identifier: GPL-3.0-or-later
 * Generated by scripts/generate-article-codec.py. Do not edit the switch tables.
 */
package org.thunderdog.challegram.data.article;

import org.drinkless.tdlib.TdApi;
import java.io.*;
import java.nio.ByteBuffer;
import java.nio.CharBuffer;
import java.nio.charset.Charset;
import java.nio.charset.CodingErrorAction;

/** Versioned local snapshots; never used as a network protocol or Java serialization. */
public final class ArticleCodec {
  private ArticleCodec () { }
  private static final int MAGIC = 0x41525431;
  private static final int MAX_BYTES = 16 * 1024 * 1024;
  private static final int MAX_ITEMS = 100000;
  private static final int MAX_DEPTH = 128;
  private static final Charset UTF8 = Charset.forName("UTF-8");
  public static final String SCHEMA = "SCHEMA_HASH";

  private static final class Budget {
    int items;
    void enter (int depth) throws IOException {
      if (depth > MAX_DEPTH || ++items > MAX_ITEMS) throw new IOException("Article snapshot exceeds structural limits");
    }
  }

  public static byte[] encode (TdApi.Object value) {
    try {
      ByteArrayOutputStream bytes = new ByteArrayOutputStream();
      DataOutputStream out = new DataOutputStream(new FilterOutputStream(bytes) {
        private int size;
        private void count (int length) throws IOException {
          if (length > MAX_BYTES - size) throw new IOException("Article snapshot is too large");
          size += length;
        }
        @Override public void write (int b) throws IOException { count(1); this.out.write(b); }
        @Override public void write (byte[] b, int offset, int length) throws IOException { count(length); this.out.write(b, offset, length); }
      });
      out.writeInt(MAGIC);
      out.writeUTF(SCHEMA);
      write(out, value, 0, new Budget());
      out.flush();
      return bytes.toByteArray();
    } catch (IOException e) {
      throw new IllegalArgumentException("Cannot snapshot article", e);
    }
  }

  public static TdApi.Object decode (byte[] bytes) throws IOException {
    if (bytes == null || bytes.length > MAX_BYTES) throw new IOException("Invalid article snapshot size");
    DataInputStream in = new DataInputStream(new ByteArrayInputStream(bytes));
    if (in.readInt() != MAGIC || !SCHEMA.equals(in.readUTF())) throw new IOException("Unsupported article snapshot version");
    try {
      TdApi.Object result = read(in, 0, new Budget());
      if (in.available() != 0) throw new IOException("Trailing article snapshot data");
      return result;
    } catch (ClassCastException e) {
      throw new IOException("Invalid article snapshot field type", e);
    }
  }

  public static <T extends TdApi.Object> T copy (T value, Class<T> type) {
    try { return type.cast(decode(encode(value))); }
    catch (IOException e) { throw new IllegalArgumentException("Invalid article snapshot", e); }
  }

  private static int length (DataInputStream in) throws IOException {
    int length = in.readInt();
    if (length < -1 || length > MAX_ITEMS || length > in.available()) throw new IOException("Invalid article array length");
    return length;
  }

  private static void writeString (DataOutputStream out, String value) throws IOException {
    if (value == null) { out.writeInt(-1); return; }
    ByteBuffer buffer = UTF8.newEncoder().onMalformedInput(CodingErrorAction.REPORT).encode(CharBuffer.wrap(value));
    int size = buffer.remaining();
    if (size > MAX_BYTES) throw new IOException("Article string is too large");
    out.writeInt(size);
    if (buffer.hasArray()) out.write(buffer.array(), buffer.arrayOffset() + buffer.position(), size);
    else while (buffer.hasRemaining()) out.writeByte(buffer.get());
  }

  private static String readString (DataInputStream in) throws IOException {
    int size = in.readInt();
    if (size == -1) return null;
    if (size < 0 || size > MAX_BYTES || size > in.available()) throw new IOException("Invalid article string size");
    byte[] bytes = new byte[size];
    in.readFully(bytes);
    return UTF8.newDecoder().onMalformedInput(CodingErrorAction.REPORT).decode(ByteBuffer.wrap(bytes)).toString();
  }

  private static void write (DataOutputStream out, TdApi.Object value, int depth, Budget budget) throws IOException {
    budget.enter(depth);
    if (value == null) { out.writeInt(0); return; }
    out.writeInt(value.getConstructor());
    switch (value.getConstructor()) {
'''.replace("SCHEMA_HASH", schema_hash)

def java_type(t):
    base = t.replace("[]", "")
    return t if base in primitive or base == "String" else "TdApi." + t

def write_field(t, expr, indent, level=0):
    if t.endswith("[]"):
        idx = "i" + str(level)
        return [indent + f"out.writeInt({expr} == null ? -1 : {expr}.length);",
                indent + f"if ({expr} != null) {{",
                indent + f"  if ({expr}.length > MAX_ITEMS) throw new IOException(\"Article array is too large\");",
                indent + f"  for (int {idx} = 0; {idx} < {expr}.length; {idx}++) {{"] + write_field(t[:-2], f"{expr}[{idx}]", indent + "    ", level + 1) + [indent + "  }", indent + "}"]
    if t == "String": return [indent + f"writeString(out, {expr});"]
    if t in primitive: return [indent + f"out.write{primitive[t]}({expr});"]
    return [indent + f"write(out, {expr}, depth + 1, budget);"]

def read_field(t, expr, indent, level=0):
    if t.endswith("[]"):
        idx, size = "i" + str(level), "n" + str(level)
        allocation = java_type(t).replace("[]", "[" + size + "]", 1)
        return [indent + "{", indent + f"  int {size} = length(in);",
                indent + f"  if ({size} >= 0) {{", indent + f"    {expr} = new {allocation};",
                indent + f"    for (int {idx} = 0; {idx} < {size}; {idx}++) {{"] + read_field(t[:-2], f"{expr}[{idx}]", indent + "      ", level + 1) + [indent + "    }", indent + "  }", indent + "}"]
    if t == "String": value = "readString(in)"
    elif t in primitive: value = f"in.read{primitive[t]}()"
    else: value = f"({java_type(t)}) read(in, depth + 1, budget)"
    return [indent + f"{expr} = {value};"]

lines = [header]
for name in concrete:
    lines.extend([f"      case TdApi.{name}.CONSTRUCTOR: {{", f"        TdApi.{name} v = (TdApi.{name}) value;"])
    for t, f in classes[name][1]: lines.extend(write_field(t, "v." + f, "        "))
    lines.extend(["        return;", "      }"])
lines.extend(['      default: throw new IOException("Unsupported article snapshot type: " + value.getConstructor());', "    }", "  }", "",
              "  private static TdApi.Object read (DataInputStream in, int depth, Budget budget) throws IOException {", "    budget.enter(depth);", "    int constructor = in.readInt();", "    switch (constructor) {", "      case 0: return null;"])
for name in concrete:
    lines.extend([f"      case TdApi.{name}.CONSTRUCTOR: {{", f"        TdApi.{name} v = new TdApi.{name}();"])
    for t, f in classes[name][1]: lines.extend(read_field(t, "v." + f, "        "))
    lines.extend(["        return v;", "      }"])
lines.extend(['      default: throw new IOException("Unsupported article snapshot constructor: " + constructor);', "    }", "  }", "",
              "  public interface Visitor { void accept (TdApi.Object value, int depth); }",
              "  public static void visit (TdApi.Object value, Visitor visitor) {",
              "    try { visit(value, visitor, 0, new Budget()); }",
              "    catch (IOException e) { throw new IllegalArgumentException(\"Invalid article tree\", e); }",
              "  }",
              "  private static void visit (TdApi.Object value, Visitor visitor, int depth, Budget budget) throws IOException {",
              "    budget.enter(depth);", "    if (value == null) return;", "    visitor.accept(value, depth);", "    switch (value.getConstructor()) {"])
def visit_field(t, expr, indent, level=0):
    base = t.replace("[]", "")
    if base in primitive or base == "String": return []
    if t.endswith("[]"):
        idx = "i" + str(level)
        return [indent + f"if ({expr} != null) {{", indent + f"  for (int {idx} = 0; {idx} < {expr}.length; {idx}++) {{"] + visit_field(t[:-2], f"{expr}[{idx}]", indent + "    ", level + 1) + [indent + "  }", indent + "}"]
    return [indent + f"visit({expr}, visitor, depth + 1, budget);"]
for name in concrete:
    lines.extend([f"      case TdApi.{name}.CONSTRUCTOR: {{", f"        TdApi.{name} v = (TdApi.{name}) value;"])
    for t, f in classes[name][1]: lines.extend(visit_field(t, "v." + f, "        "))
    lines.extend(["        return;", "      }"])
lines.extend(['      default: throw new IOException("Unsupported article tree constructor: " + value.getConstructor());', "    }", "  }", "}", ""])
DEST.parent.mkdir(parents=True, exist_ok=True)
DEST.write_text("\n".join(lines), encoding="utf-8", newline="\n")
print(f"Generated {len(concrete)} typed constructors, schema {schema_hash}")
