package me.vkryl.task

import getOrThrow
import loadProperties
import org.gradle.api.tasks.TaskAction
import kotlin.contracts.ExperimentalContracts

open class UpdateExceptionsTask : BaseTask() {
  @ExperimentalContracts
  @TaskAction
  fun updateExceptions () {
    val appVersion = loadProperties("version.properties").getOrThrow("version.app").toInt()
    if (appVersion == 0)
      error("appVersion == 0")
    writeToFile("app/src/main/java/org/drinkmore/ClientException.java") { java ->
      java.append("""
        package org.drinkmore;

        import org.thunderdog.challegram.BuildConfig;

        import me.vkryl.annotation.Autogenerated;

        @Autogenerated
        public abstract class ClientException extends RuntimeException {
          private ClientException (String message) {
            super(message);
          }

          private static class ClientException_${appVersion} extends ClientException {
            private ClientException_${appVersion} (String message) {
              super(Tracer.format(message));
            }
          }

          static final class DatabaseError extends ClientException_${appVersion} {
            DatabaseError (String message) {
              super(message + ", versionCode: " + BuildConfig.VERSION_CODE);
            }
          }

          static final class TdlibLaunchError extends ClientException_${appVersion} {
            TdlibLaunchError (String message) {
              super(message);
            }
          }

          static final class TdlibLostPromiseError extends ClientException_${appVersion} {
            TdlibLostPromiseError (String message) {
              super(message);
            }
          }

          static void throwTestError (Throwable error) {
            throw new ClientException_${appVersion}(error.getMessage());
          }

          static void throwAssertionError (Throwable error) {
            throw new ClientException_${appVersion}(error.getMessage());
          }
        }
      """.trimIndent())
    }
  }
}